package com.game.message.pool;
	
import java.util.HashMap;import com.game.shop.message.BuyItemMessage;
import com.game.shop.handler.BuyItemHandler;
import com.game.shop.message.SellItemMessage;
import com.game.shop.handler.SellItemHandler;
import com.game.equip.message.WearEquipMessage;
import com.game.equip.handler.WearEquipHandler;
import com.game.equip.message.UnwearEquipMessage;
import com.game.equip.handler.UnwearEquipHandler;
import com.game.skill.message.StudySkillMessage;
import com.game.skill.handler.StudySkillHandler;
import com.game.skill.message.LevelUpSkillMessage;
import com.game.skill.handler.LevelUpSkillHandler;
import com.game.shortcut.message.AddShortCutMessage;
import com.game.shortcut.handler.AddShortCutHandler;
import com.game.shortcut.message.RemoveShortCutMessage;
import com.game.shortcut.handler.RemoveShortCutHandler;
import com.game.gm.message.GmCommandMessage;
import com.game.gm.handler.GmCommandHandler;
import com.game.log.message.LogInfoMessage;
import com.game.log.handler.LogInfoHandler;
import com.game.skill.message.SetDefaultSkillMessage;
import com.game.skill.handler.SetDefaultSkillHandler;
import com.game.chat.message.ChatRequestMessage;
import com.game.chat.handler.ChatRequestHandler;
import com.game.shop.message.ReqNotSaleMessage;
import com.game.shop.handler.ReqNotSaleHandler;
import com.game.shortcut.message.MoveShortCutMessage;
import com.game.shortcut.handler.MoveShortCutHandler;
import com.game.shop.message.ReqRebuyListMessage;
import com.game.shop.handler.ReqRebuyListHandler;
import com.game.shop.message.ReqRebuyMessage;
import com.game.shop.handler.ReqRebuyHandler;
import com.game.buff.message.ReqRemoveBuffMessage;
import com.game.buff.handler.ReqRemoveBuffHandler;
import com.game.buff.message.ReqBuffInfoMessage;
import com.game.buff.handler.ReqBuffInfoHandler;
import com.game.skill.message.ReqCompleteMomentMessage;
import com.game.skill.handler.ReqCompleteMomentHandler;
import com.game.skill.message.NowLearnSkillQueryMessage;
import com.game.skill.handler.NowLearnSkillQueryHandler;
import com.game.chat.message.RoleQueryMessage;
import com.game.chat.handler.RoleQueryHandler;
import com.game.server.message.ResRegisterGateMessage;
import com.game.server.handler.ResRegisterGateHandler;
import com.game.server.message.ResRegisterWorldMessage;
import com.game.server.handler.ResRegisterWorldHandler;
import com.game.login.message.ReqLoginCharacterToGameMessage;
import com.game.login.handler.ReqLoginCharacterToGameHandler;
import com.game.login.message.ReqCreateCharacterToGameMessage;
import com.game.login.handler.ReqCreateCharacterToGameHandler;
import com.game.login.message.ReqLoadFinishMessage;
import com.game.login.handler.ReqLoadFinishHandler;
import com.game.login.message.ReqQuitToGameMessage;
import com.game.login.handler.ReqQuitToGameHandler;
import com.game.dianjiangchun.message.GetDianjiangchunInfoToServerMessage;
import com.game.dianjiangchun.handler.GetDianjiangchunInfoToServerHandler;
import com.game.dianjiangchun.message.GetBeginDianjiangchunToServerMessage;
import com.game.dianjiangchun.handler.GetBeginDianjiangchunToServerHandler;
import com.game.dianjiangchun.message.GetChangeLuckToServerMessage;
import com.game.dianjiangchun.handler.GetChangeLuckToServerHandler;
import com.game.dianjiangchun.message.GetReceiveintinfuriatingvalueToServerMessage;
import com.game.dianjiangchun.handler.GetReceiveintinfuriatingvalueToServerHandler;
import com.game.team.message.ReqCreateateamGameMessage;
import com.game.team.handler.ReqCreateateamGameHandler;
import com.game.team.message.ReqApplyGameMessage;
import com.game.team.handler.ReqApplyGameHandler;
import com.game.team.message.ReqApplyGameSelectMessage;
import com.game.team.handler.ReqApplyGameSelectHandler;
import com.game.team.message.ReqInviteGameMessage;
import com.game.team.handler.ReqInviteGameHandler;
import com.game.team.message.ReqInviteGameSelectMessage;
import com.game.team.handler.ReqInviteGameSelectHandler;
import com.game.team.message.ReqToleaveGameMessage;
import com.game.team.handler.ReqToleaveGameHandler;
import com.game.team.message.ReqAppointGameMessage;
import com.game.team.handler.ReqAppointGameHandler;
import com.game.team.message.ReqAppointGameSelectMessage;
import com.game.team.handler.ReqAppointGameSelectHandler;
import com.game.team.message.ReqAutoTeaminvitedGameMessage;
import com.game.team.handler.ReqAutoTeaminvitedGameHandler;
import com.game.team.message.ReqAutoIntoTeamApplyGameMessage;
import com.game.team.handler.ReqAutoIntoTeamApplyGameHandler;
import com.game.team.message.ResTeamGameMessage;
import com.game.team.handler.ResTeamGameHandler;
import com.game.team.message.ResToleaveWorldMessage;
import com.game.team.handler.ResToleaveWorldHandler;
import com.game.map.message.ReqRunningMessage;
import com.game.map.handler.ReqRunningHandler;
import com.game.map.message.ReqJumpMessage;
import com.game.map.handler.ReqJumpHandler;
import com.game.map.message.ReqStartBlockMessage;
import com.game.map.handler.ReqStartBlockHandler;
import com.game.map.message.ReqStopBlockMessage;
import com.game.map.handler.ReqStopBlockHandler;
import com.game.map.message.ReqPlayerStopMessage;
import com.game.map.handler.ReqPlayerStopHandler;
import com.game.map.message.ReqChangeMapByMoveMessage;
import com.game.map.handler.ReqChangeMapByMoveHandler;
import com.game.map.message.ReqEnterMapMessage;
import com.game.map.handler.ReqEnterMapHandler;
import com.game.team.message.ReqUpdateTeaminfoGameMessage;
import com.game.team.handler.ReqUpdateTeaminfoGameHandler;
import com.game.friend.message.ReqRelationGetListToServerMessage;
import com.game.friend.handler.ReqRelationGetListToServerHandler;
import com.game.friend.message.ReqRelationAddToServerMessage;
import com.game.friend.handler.ReqRelationAddToServerHandler;
import com.game.friend.message.ReqRelationDeleteToServerMessage;
import com.game.friend.handler.ReqRelationDeleteToServerHandler;
import com.game.friend.message.ReqRelationSortToServerMessage;
import com.game.friend.handler.ReqRelationSortToServerHandler;
import com.game.friend.message.ReqRelationMoodToServerMessage;
import com.game.friend.handler.ReqRelationMoodToServerHandler;
import com.game.backpack.message.ReqGetItemsMessage;
import com.game.backpack.handler.ReqGetItemsHandler;
import com.game.backpack.message.ReqMoveItemMessage;
import com.game.backpack.handler.ReqMoveItemHandler;
import com.game.backpack.message.ReqUseItemMessage;
import com.game.backpack.handler.ReqUseItemHandler;
import com.game.backpack.message.ReqDelItemMessage;
import com.game.backpack.handler.ReqDelItemHandler;
import com.game.backpack.message.ReqClearUpGoodsMessage;
import com.game.backpack.handler.ReqClearUpGoodsHandler;
import com.game.backpack.message.ReqOpenCellMessage;
import com.game.backpack.handler.ReqOpenCellHandler;
import com.game.backpack.message.ReqCellTimeQueryMessage;
import com.game.backpack.handler.ReqCellTimeQueryHandler;
import com.game.backpack.message.ReqDiscardMessage;
import com.game.backpack.handler.ReqDiscardHandler;
import com.game.backpack.message.ReqDestroyMessage;
import com.game.backpack.handler.ReqDestroyHandler;
import com.game.store.message.ReqStoreGetItemsMessage;
import com.game.store.handler.ReqStoreGetItemsHandler;
import com.game.store.message.ReqStoreMoveItemMessage;
import com.game.store.handler.ReqStoreMoveItemHandler;
import com.game.store.message.ReqStoreClearUpMessage;
import com.game.store.handler.ReqStoreClearUpHandler;
import com.game.store.message.ReqStoreOpenCellMessage;
import com.game.store.handler.ReqStoreOpenCellHandler;
import com.game.store.message.ReqStoreCellTimeQueryMessage;
import com.game.store.handler.ReqStoreCellTimeQueryHandler;
import com.game.store.message.ReqBagToStoreMessage;
import com.game.store.handler.ReqBagToStoreHandler;
import com.game.store.message.ReqStoreToBagMessage;
import com.game.store.handler.ReqStoreToBagHandler;
import com.game.transactions.message.ReqTransactionsLaunchMessage;
import com.game.transactions.handler.ReqTransactionsLaunchHandler;
import com.game.transactions.message.ReqTransactionsAcceptMessage;
import com.game.transactions.handler.ReqTransactionsAcceptHandler;
import com.game.transactions.message.ReqTransactionsRefuseMessage;
import com.game.transactions.handler.ReqTransactionsRefuseHandler;
import com.game.transactions.message.ReqTransactionsCanceledMessage;
import com.game.transactions.handler.ReqTransactionsCanceledHandler;
import com.game.transactions.message.ReqTransactionsIntoItemMessage;
import com.game.transactions.handler.ReqTransactionsIntoItemHandler;
import com.game.transactions.message.ReqTransactionsRemoveItemMessage;
import com.game.transactions.handler.ReqTransactionsRemoveItemHandler;
import com.game.transactions.message.ReqTransactionsChangeGoldMessage;
import com.game.transactions.handler.ReqTransactionsChangeGoldHandler;
import com.game.transactions.message.ReqTransactionsChangeYuanbaoMessage;
import com.game.transactions.handler.ReqTransactionsChangeYuanbaoHandler;
import com.game.transactions.message.ReqTransactionsSetStateMessage;
import com.game.transactions.handler.ReqTransactionsSetStateHandler;
import com.game.transactions.message.ReqCanreceiveYuanbaoMessage;
import com.game.transactions.handler.ReqCanreceiveYuanbaoHandler;
import com.game.transactions.message.ReqAutorefusaldealMessage;
import com.game.transactions.handler.ReqAutorefusaldealHandler;
import com.game.fight.message.ReqAttackMonsterMessage;
import com.game.fight.handler.ReqAttackMonsterHandler;
import com.game.fight.message.ReqAttackPlayerMessage;
import com.game.fight.handler.ReqAttackPlayerHandler;
import com.game.task.message.ReqTaskReceiveMessage;
import com.game.task.handler.ReqTaskReceiveHandler;
import com.game.task.message.ReqTaskFinshMessage;
import com.game.task.handler.ReqTaskFinshHandler;
import com.game.task.message.ReqTaskUpAchieveMessage;
import com.game.task.handler.ReqTaskUpAchieveHandler;
import com.game.task.message.ReqTaskDownHardMessage;
import com.game.task.handler.ReqTaskDownHardHandler;
import com.game.task.message.ReqReceiveRewardsMessage;
import com.game.task.handler.ReqReceiveRewardsHandler;
import com.game.task.message.ReqQuickFinshMessage;
import com.game.task.handler.ReqQuickFinshHandler;
import com.game.map.message.ReqLoadFinishForChangeMapToGameMessage;
import com.game.map.handler.ReqLoadFinishForChangeMapToGameHandler;
import com.game.backpack.message.ReqTakeUpMessage;
import com.game.backpack.handler.ReqTakeUpHandler;
import com.game.guild.message.ReqGuildCreateToServerMessage;
import com.game.guild.handler.ReqGuildCreateToServerHandler;
import com.game.guild.message.ReqGuildAutoArgeeAddGuildToServerMessage;
import com.game.guild.handler.ReqGuildAutoArgeeAddGuildToServerHandler;
import com.game.guild.message.ReqGuildGetGuildListToServerMessage;
import com.game.guild.handler.ReqGuildGetGuildListToServerHandler;
import com.game.guild.message.ReqGuildApplyAddToServerMessage;
import com.game.guild.handler.ReqGuildApplyAddToServerHandler;
import com.game.guild.message.ReqGuildInviteAddToServerMessage;
import com.game.guild.handler.ReqGuildInviteAddToServerHandler;
import com.game.guild.message.ReqGuildGetMemberListToServerMessage;
import com.game.guild.handler.ReqGuildGetMemberListToServerHandler;
import com.game.guild.message.ReqGuildAddMemberToServerMessage;
import com.game.guild.handler.ReqGuildAddMemberToServerHandler;
import com.game.guild.message.ReqGuildQuitToServerMessage;
import com.game.guild.handler.ReqGuildQuitToServerHandler;
import com.game.guild.message.ReqGuildChangeNickNameToServerMessage;
import com.game.guild.handler.ReqGuildChangeNickNameToServerHandler;
import com.game.guild.message.ReqGuildChangePowerLevelToServerMessage;
import com.game.guild.handler.ReqGuildChangePowerLevelToServerHandler;
import com.game.guild.message.ReqGuildDeleteMemberToServerMessage;
import com.game.guild.handler.ReqGuildDeleteMemberToServerHandler;
import com.game.guild.message.ReqGuildAutoGuildArgeeAddToServerMessage;
import com.game.guild.handler.ReqGuildAutoGuildArgeeAddToServerHandler;
import com.game.guild.message.ReqGuildChangeBulletinToServerMessage;
import com.game.guild.handler.ReqGuildChangeBulletinToServerHandler;
import com.game.guild.message.ReqGuildSubmitItemToServerMessage;
import com.game.guild.handler.ReqGuildSubmitItemToServerHandler;
import com.game.guild.message.ReqGuildChangeBannerIconToServerMessage;
import com.game.guild.handler.ReqGuildChangeBannerIconToServerHandler;
import com.game.guild.message.ReqGuildChangeBannerNameToServerMessage;
import com.game.guild.handler.ReqGuildChangeBannerNameToServerHandler;
import com.game.guild.message.ReqGuildBannerLevelUpToServerMessage;
import com.game.guild.handler.ReqGuildBannerLevelUpToServerHandler;
import com.game.guild.message.ReqGuildAddDiplomaticToServerMessage;
import com.game.guild.handler.ReqGuildAddDiplomaticToServerHandler;
import com.game.guild.message.ReqGuildDeleteDiplomaticToServerMessage;
import com.game.guild.handler.ReqGuildDeleteDiplomaticToServerHandler;
import com.game.guild.message.ReqGuildDeleteGuildToServerMessage;
import com.game.guild.handler.ReqGuildDeleteGuildToServerHandler;
import com.game.guild.message.ReqGuildGetEventListToServerMessage;
import com.game.guild.handler.ReqGuildGetEventListToServerHandler;
import com.game.guild.message.ResInnerGuildAloneGuildInfoToServerMessage;
import com.game.guild.handler.ResInnerGuildAloneGuildInfoToServerHandler;
import com.game.guild.message.ResInnerGuildAloneMemberInfoToServerMessage;
import com.game.guild.handler.ResInnerGuildAloneMemberInfoToServerHandler;
import com.game.player.message.ReqReviveMessage;
import com.game.player.handler.ReqReviveHandler;
import com.game.player.message.ReqLocalReviveMessage;
import com.game.player.handler.ReqLocalReviveHandler;
import com.game.player.message.ReqOtherPlayerInfoMessage;
import com.game.player.handler.ReqOtherPlayerInfoHandler;
import com.game.player.message.ReqChangePKStateMessage;
import com.game.player.handler.ReqChangePKStateHandler;
import com.game.player.message.ReqAutoStartMessage;
import com.game.player.handler.ReqAutoStartHandler;
import com.game.player.message.ReqAutoEndMessage;
import com.game.player.handler.ReqAutoEndHandler;
import com.game.team.message.ReqMapSearchTeamInfoGameMessage;
import com.game.team.handler.ReqMapSearchTeamInfoGameHandler;
import com.game.team.message.ReqMapSearchPlayerInfoGameMessage;
import com.game.team.handler.ReqMapSearchPlayerInfoGameHandler;
import com.game.map.message.ReqNpcTransMessage;
import com.game.map.handler.ReqNpcTransHandler;
import com.game.task.message.ReqTaskInfoMationMessage;
import com.game.task.handler.ReqTaskInfoMationHandler;
import com.game.task.message.ReqConquerTaskDevourMessage;
import com.game.task.handler.ReqConquerTaskDevourHandler;
import com.game.stalls.message.ReqStallsOpenUpMessage;
import com.game.stalls.handler.ReqStallsOpenUpHandler;
import com.game.stalls.message.ReqStallsPlayerIdLookMessage;
import com.game.stalls.handler.ReqStallsPlayerIdLookHandler;
import com.game.stalls.message.ReqStallsSortMessage;
import com.game.stalls.handler.ReqStallsSortHandler;
import com.game.stalls.message.ReqStallsBuyMessage;
import com.game.stalls.handler.ReqStallsBuyHandler;
import com.game.stalls.message.ReqStallsProductWasAddedMessage;
import com.game.stalls.handler.ReqStallsProductWasAddedHandler;
import com.game.stalls.message.ReqStallsAdjustPricesMessage;
import com.game.stalls.handler.ReqStallsAdjustPricesHandler;
import com.game.stalls.message.ReqStallsOffShelfMessage;
import com.game.stalls.handler.ReqStallsOffShelfHandler;
import com.game.stalls.message.ReqStallsSearchMessage;
import com.game.stalls.handler.ReqStallsSearchHandler;
import com.game.stalls.message.ReqStallsLooklogMessage;
import com.game.stalls.handler.ReqStallsLooklogHandler;
import com.game.stalls.message.ReqChangeStallsNameMessage;
import com.game.stalls.handler.ReqChangeStallsNameHandler;
import com.game.monster.message.ResMonsterSyncMessage;
import com.game.monster.handler.ResMonsterSyncHandler;
import com.game.mail.message.ReqMailQueryListToServerMessage;
import com.game.mail.handler.ReqMailQueryListToServerHandler;
import com.game.mail.message.ReqMailQueryDetailToServerMessage;
import com.game.mail.handler.ReqMailQueryDetailToServerHandler;
import com.game.mail.message.ReqMailGetItemToServerMessage;
import com.game.mail.handler.ReqMailGetItemToServerHandler;
import com.game.mail.message.ReqMailSendNewMailToServerMessage;
import com.game.mail.handler.ReqMailSendNewMailToServerHandler;
import com.game.mail.message.ReqMailDeleteMailToServerMessage;
import com.game.mail.handler.ReqMailDeleteMailToServerHandler;
import com.game.mail.message.ReqMailQueryUserToServerMessage;
import com.game.mail.handler.ReqMailQueryUserToServerHandler;
import com.game.mail.message.ReqMailReturnToServerMessage;
import com.game.mail.handler.ReqMailReturnToServerHandler;
import com.game.transactions.message.ReqOpenTmpYuanbaoPanelMessage;
import com.game.transactions.handler.ReqOpenTmpYuanbaoPanelHandler;
import com.game.transactions.message.ReqGetTmpYuanbaoMessage;
import com.game.transactions.handler.ReqGetTmpYuanbaoHandler;
import com.game.stalls.message.ResStallsBuycheckToGameMessage;
import com.game.stalls.handler.ResStallsBuycheckToGameHandler;
import com.game.stalls.message.ResStallsBuyDeductingToGameMessage;
import com.game.stalls.handler.ResStallsBuyDeductingToGameHandler;
import com.game.stalls.message.ResStallsBuyAddMoneyToGameMessage;
import com.game.stalls.handler.ResStallsBuyAddMoneyToGameHandler;
import com.game.stalls.message.ResStallsBuyDeductingFailToGameMessage;
import com.game.stalls.handler.ResStallsBuyDeductingFailToGameHandler;
import com.game.stalls.message.ResStallsProductWasAddedFailToGameMessage;
import com.game.stalls.handler.ResStallsProductWasAddedFailToGameHandler;
import com.game.stalls.message.ResStallsOffShelfToGameMessage;
import com.game.stalls.handler.ResStallsOffShelfToGameHandler;
import com.game.login.message.ResPlayerWorldInfoMessage;
import com.game.login.handler.ResPlayerWorldInfoHandler;
import com.game.longyuan.message.ReqLongYuanOpenMessage;
import com.game.longyuan.handler.ReqLongYuanOpenHandler;
import com.game.longyuan.message.ReqLongYuanActivationMessage;
import com.game.longyuan.handler.ReqLongYuanActivationHandler;
import com.game.longyuan.message.ReqLongYuanTipsMessage;
import com.game.longyuan.handler.ReqLongYuanTipsHandler;
import com.game.longyuan.message.ReqLongYuanStarMapTipsMessage;
import com.game.longyuan.handler.ReqLongYuanStarMapTipsHandler;
import com.game.player.message.ReqOtherPlayerInfoToGameMessage;
import com.game.player.handler.ReqOtherPlayerInfoToGameHandler;
import com.game.login.message.ResPlayerNonageToGameMessage;
import com.game.login.handler.ResPlayerNonageToGameHandler;
import com.game.player.message.ReqNonageTimeMessage;
import com.game.player.handler.ReqNonageTimeHandler;
import com.game.friend.message.ResInnerRelationSendListToWorldMessage;
import com.game.friend.handler.ResInnerRelationSendListToWorldHandler;
import com.game.player.message.ReqPlayerNonageRegisterMessage;
import com.game.player.handler.ReqPlayerNonageRegisterHandler;
import com.game.team.message.ReqMapSearchMemberNameGameMessage;
import com.game.team.handler.ReqMapSearchMemberNameGameHandler;
import com.game.team.message.ReqGenericSearchToGameMessage;
import com.game.team.handler.ReqGenericSearchToGameHandler;
import com.game.friend.message.ReqRelationConfigToServerMessage;
import com.game.friend.handler.ReqRelationConfigToServerHandler;
import com.game.setupmenu.message.ReqGetMenuStatusMessage;
import com.game.setupmenu.handler.ReqGetMenuStatusHandler;
import com.game.setupmenu.message.ReqSetMenuStatusMessage;
import com.game.setupmenu.handler.ReqSetMenuStatusHandler;
import com.game.horse.message.ReqGethorseInfoMessage;
import com.game.horse.handler.ReqGethorseInfoHandler;
import com.game.horse.message.ReqChangeRidingStateMessage;
import com.game.horse.handler.ReqChangeRidingStateHandler;
import com.game.horse.message.ReqhorseStageUpPanelMessage;
import com.game.horse.handler.ReqhorseStageUpPanelHandler;
import com.game.horse.message.ReqhorseStageUpStartMessage;
import com.game.horse.handler.ReqhorseStageUpStartHandler;
import com.game.horse.message.ReqhorseLuckyRodMessage;
import com.game.horse.handler.ReqhorseLuckyRodHandler;
import com.game.horse.message.ReqhorseLuckyPenteMessage;
import com.game.horse.handler.ReqhorseLuckyPenteHandler;
import com.game.horse.message.ReqhorseReceiveMessage;
import com.game.horse.handler.ReqhorseReceiveHandler;
import com.game.horse.message.ReqhorseClearCDMessage;
import com.game.horse.handler.ReqhorseClearCDHandler;
import com.game.map.message.ReqGoldMapTransMessage;
import com.game.map.handler.ReqGoldMapTransHandler;
import com.game.fightpower.message.ReqFightPowerToServerMessage;
import com.game.fightpower.handler.ReqFightPowerToServerHandler;
import com.game.zones.message.ReqZonePanelSelectMessage;
import com.game.zones.handler.ReqZonePanelSelectHandler;
import com.game.zones.message.ReqZoneIntoMessage;
import com.game.zones.handler.ReqZoneIntoHandler;
import com.game.zones.message.ReqZoneOutMessage;
import com.game.zones.handler.ReqZoneOutHandler;
import com.game.horse.message.ReqOpenSkillUpPanelMessage;
import com.game.horse.handler.ReqOpenSkillUpPanelHandler;
import com.game.player.message.ReqPlayerAvatarChangeMessage;
import com.game.player.handler.ReqPlayerAvatarChangeHandler;
import com.game.friend.message.ResInnerRelationAddNoticeMessage;
import com.game.friend.handler.ResInnerRelationAddNoticeHandler;
import com.game.gift.message.ReqGetGiftItemsToServerMessage;
import com.game.gift.handler.ReqGetGiftItemsToServerHandler;
import com.game.horse.message.ReqSkillInfoMessage;
import com.game.horse.handler.ReqSkillInfoHandler;
import com.game.horse.message.ReqChangeHorseMessage;
import com.game.horse.handler.ReqChangeHorseHandler;
import com.game.equipstreng.message.ReqStrengItemToServerMessage;
import com.game.equipstreng.handler.ReqStrengItemToServerHandler;
import com.game.equipstreng.message.ReqStageUpItemToServerMessage;
import com.game.equipstreng.handler.ReqStageUpItemToServerHandler;
import com.game.equipstreng.message.ReqStrengClearCoolingMessage;
import com.game.equipstreng.handler.ReqStrengClearCoolingHandler;
import com.game.equipstreng.message.ReqStrengthenStateMessage;
import com.game.equipstreng.handler.ReqStrengthenStateHandler;
import com.game.team.message.ReqIntoTeamToGameMessage;
import com.game.team.handler.ReqIntoTeamToGameHandler;
import com.game.plugset.message.ReqPlugSetInfoMessage;
import com.game.plugset.handler.ReqPlugSetInfoHandler;
import com.game.player.message.ReqPlayerCheckOnlineMessage;
import com.game.player.handler.ReqPlayerCheckOnlineHandler;
import com.game.player.message.ReqGetPlayerAppearanceInfoMessage;
import com.game.player.handler.ReqGetPlayerAppearanceInfoHandler;
import com.game.player.message.ReqDelPlayerToGameMessage;
import com.game.player.handler.ReqDelPlayerToGameHandler;
import com.game.map.message.ReqGetLinesMessage;
import com.game.map.handler.ReqGetLinesHandler;
import com.game.map.message.ReqSelectLineMessage;
import com.game.map.handler.ReqSelectLineHandler;
import com.game.gem.message.ReqOpenGemPanelMessage;
import com.game.gem.handler.ReqOpenGemPanelHandler;
import com.game.gem.message.ReqGemIntoMessage;
import com.game.gem.handler.ReqGemIntoHandler;
import com.game.gem.message.ReqGemActivationORUpMessage;
import com.game.gem.handler.ReqGemActivationORUpHandler;
import com.game.shop.message.ReqShopListMessage;
import com.game.shop.handler.ReqShopListHandler;
import com.game.player.message.ResPlayerNameInfoToGameMessage;
import com.game.player.handler.ResPlayerNameInfoToGameHandler;
import com.game.player.message.ReqChangePlayerNameMessage;
import com.game.player.handler.ReqChangePlayerNameHandler;
import com.game.player.message.ResChangePlayerNameToGameMessage;
import com.game.player.handler.ResChangePlayerNameToGameHandler;
import com.game.recharge.message.RechargeMessage;
import com.game.recharge.handler.RechargeHandler;
import com.game.team.message.ResTeamchangeToGameMessage;
import com.game.team.handler.ResTeamchangeToGameHandler;
import com.game.server.message.ReqCloseForGameMessage;
import com.game.server.handler.ReqCloseForGameHandler;
import com.game.backend.message.ReqPlayerMoneyGoldToGameMessage;
import com.game.backend.handler.ReqPlayerMoneyGoldToGameHandler;
import com.game.backend.message.ReqPlayerInfoToGameMessage;
import com.game.backend.handler.ReqPlayerInfoToGameHandler;
import com.game.spirittree.message.ReqGetAllFruitInfoToGameMessage;
import com.game.spirittree.handler.ReqGetAllFruitInfoToGameHandler;
import com.game.spirittree.message.ReqGetSingleFruitInfoToGameMessage;
import com.game.spirittree.handler.ReqGetSingleFruitInfoToGameHandler;
import com.game.spirittree.message.ReqRipeningFruitToGameMessage;
import com.game.spirittree.handler.ReqRipeningFruitToGameHandler;
import com.game.spirittree.message.ReqOpenGuildFruitToGameMessage;
import com.game.spirittree.handler.ReqOpenGuildFruitToGameHandler;
import com.game.spirittree.message.ResGameMakeFruitInfoMessage;
import com.game.spirittree.handler.ResGameMakeFruitInfoHandler;
import com.game.map.message.ReqChangeDirectMessage;
import com.game.map.handler.ReqChangeDirectHandler;
import com.game.spirittree.message.ReqGuildFruitOperatingToGameMessage;
import com.game.spirittree.handler.ReqGuildFruitOperatingToGameHandler;
import com.game.spirittree.message.ResFruitOperatingToGameMessage;
import com.game.spirittree.handler.ResFruitOperatingToGameHandler;
import com.game.dazuo.message.ReqDazuoMessage;
import com.game.dazuo.handler.ReqDazuoHandler;
import com.game.dazuo.message.ReqShuangXiuMessage;
import com.game.dazuo.handler.ReqShuangXiuHandler;
import com.game.dazuo.message.ReqAgreeShuangXiuMessage;
import com.game.dazuo.handler.ReqAgreeShuangXiuHandler;
import com.game.dazuo.message.ReqRefuseShuangXiuMessage;
import com.game.dazuo.handler.ReqRefuseShuangXiuHandler;
import com.game.version.message.ResVersionUpdateToGameMessage;
import com.game.version.handler.ResVersionUpdateToGameHandler;
import com.game.card.message.ReqCardToServerMessage;
import com.game.card.handler.ReqCardToServerHandler;
import com.game.card.message.ResInnerCardToServerMessage;
import com.game.card.handler.ResInnerCardToServerHandler;
import com.game.activities.message.ReqGetRewardMessage;
import com.game.activities.message.ReqReceiveMobileGiftInfoMessage;
import com.game.activities.message.ReqReceiveMobileGiftMessage;
import com.game.activities.handler.ReqGetRewardHandler;
import com.game.activities.handler.ReqReceiveMobileGiftHandler;
import com.game.activities.handler.ReqReceiveMobileGiftInfoHandler;
import com.game.activities.message.ReqActivitiesInfoMessage;
import com.game.activities.handler.ReqActivitiesInfoHandler;
import com.game.spirittree.message.ReqRipeningDecYBToGameMessage;
import com.game.spirittree.handler.ReqRipeningDecYBToGameHandler;
import com.game.backend.message.ReqJinYanMessage;
import com.game.backend.handler.ReqJinYanHandler;
import com.game.ybcard.message.ReqYBCardToGameMessage;
import com.game.ybcard.handler.ReqYBCardToGameHandler;
import com.game.ybcard.message.ResYBCardReceiveToGameMessage;
import com.game.ybcard.handler.ResYBCardReceiveToGameHandler;
import com.game.ybcard.message.ResYBCardNoticeToGameMessage;
import com.game.ybcard.handler.ResYBCardNoticeToGameHandler;
import com.game.ybcard.message.ResYBCardAddYBPlayerToGameMessage;
import com.game.ybcard.handler.ResYBCardAddYBPlayerToGameHandler;
import com.game.spirittree.message.ReqGuildFruitLogToGameMessage;
import com.game.spirittree.handler.ReqGuildFruitLogToGameHandler;
import com.game.backend.message.ReqChangePlayerCurrencyMessage;
import com.game.backend.handler.ReqChangePlayerCurrencyHandler;
import com.game.spirittree.message.ResGuildAccExpToWorldMessage;
import com.game.spirittree.handler.ResGuildAccExpToWorldHandler;
import com.game.plugset.message.ReqPlugBackToCityMessage;
import com.game.plugset.handler.ReqPlugBackToCityHandler;
import com.game.gift.message.ReqGetOtherGiftItemsToServerMessage;
import com.game.gift.handler.ReqGetOtherGiftItemsToServerHandler;
import com.game.shop.message.ReqSellItemsMessage;
import com.game.shop.handler.ReqSellItemsHandler;
import com.game.zones.message.ReqZoneImmediatelyMessage;
import com.game.zones.handler.ReqZoneImmediatelyHandler;
import com.game.zones.message.ReqZoneOpenPanelMessage;
import com.game.zones.handler.ReqZoneOpenPanelHandler;
import com.game.zones.message.ReqSelectAwardMessage;
import com.game.zones.handler.ReqSelectAwardHandler;
import com.game.player.message.ReqScriptCommonPlayerToServerMessage;
import com.game.player.handler.ReqScriptCommonPlayerToServerHandler;
import com.game.zones.message.ReqZoneReceiveawardsMessage;
import com.game.zones.handler.ReqZoneReceiveawardsHandler;
import com.game.npc.message.ReqNpcServicesMessage;
import com.game.npc.handler.ReqNpcServicesHandler;
import com.game.npc.message.ReqServiceMessage;
import com.game.npc.handler.ReqServiceHandler;
import com.game.mail.message.ReqMailListGetItemToServerMessage;
import com.game.mail.handler.ReqMailListGetItemToServerHandler;
import com.game.toplist.message.ReqGetTopListToServerMessage;
import com.game.toplist.handler.ReqGetTopListToServerHandler;
import com.game.toplist.message.ReqWorShipToServerMessage;
import com.game.toplist.handler.ReqWorShipToServerHandler;
import com.game.toplist.message.ResGetTopAwardToServerMessage;
import com.game.toplist.handler.ResGetTopAwardToServerHandler;
import com.game.fight.message.ReqChangeAttackTargetMessage;
import com.game.fight.handler.ReqChangeAttackTargetHandler;
import com.game.fight.message.ReqAttackPetMessage;
import com.game.fight.handler.ReqAttackPetHandler;
import com.game.epalace.message.ReqEpalaceDiceToGameMessage;
import com.game.epalace.handler.ReqEpalaceDiceToGameHandler;
import com.game.epalace.message.ReqEpalaceOpenToGameMessage;
import com.game.epalace.handler.ReqEpalaceOpenToGameHandler;
import com.game.task.message.ResGiveUpTaskMessage;
import com.game.task.handler.ResGiveUpTaskHandler;
import com.game.task.message.ReqGiveUpTaskMessage;
import com.game.task.handler.ReqGiveUpTaskHandler;
import com.game.toplist.message.ReqChangeTitleToServerMessage;
import com.game.toplist.handler.ReqChangeTitleToServerHandler;
import com.game.toplist.message.ResGetTopTitleToServerMessage;
import com.game.toplist.handler.ResGetTopTitleToServerHandler;
import com.game.epalace.message.ReqEpalaceTaskEndToGameMessage;
import com.game.epalace.handler.ReqEpalaceTaskEndToGameHandler;
import com.game.epalace.message.ReqEpalaceAbandonTaskToGameMessage;
import com.game.epalace.handler.ReqEpalaceAbandonTaskToGameHandler;
import com.game.player.message.ResScriptCommonServerToServerMessage;
import com.game.player.handler.ResScriptCommonServerToServerHandler;
import com.game.task.message.ResTargetMonsterToServerMessage;
import com.game.task.handler.ResTargetMonsterToServerHandler;
import com.game.mail.message.ResMailSendSystemMailToServerMessage;
import com.game.mail.handler.ResMailSendSystemMailToServerHandler;
import com.game.zones.message.ResfastestClearanceToGameMessage;
import com.game.zones.handler.ResfastestClearanceToGameHandler;
import com.game.monster.message.ReqQueryBossListMessage;
import com.game.monster.handler.ReqQueryBossListHandler;
import com.game.monster.message.ReqQueryBossStateListMessage;
import com.game.monster.handler.ReqQueryBossStateListHandler;
import com.game.challenge.message.ReqOpenChallengeToGameMessage;
import com.game.challenge.handler.ReqOpenChallengeToGameHandler;
import com.game.challenge.message.ReqSelectChallengeToGameMessage;
import com.game.challenge.handler.ReqSelectChallengeToGameHandler;
import com.game.pet.message.ReqShowPetMessage;
import com.game.pet.handler.ReqShowPetHandler;
import com.game.pet.message.ReqHiddenPetMessage;
import com.game.pet.handler.ReqHiddenPetHandler;
import com.game.pet.message.ReqPetListQueryMessage;
import com.game.pet.handler.ReqPetListQueryHandler;
import com.game.pet.message.ReqPetHeTiMessage;
import com.game.pet.handler.ReqPetHeTiHandler;
import com.game.pet.message.ReqPetChangeSkillMessage;
import com.game.pet.handler.ReqPetChangeSkillHandler;
import com.game.pet.message.ReqGoldReiveMessage;
import com.game.pet.handler.ReqGoldReiveHandler;
import com.game.pet.message.ReqGotPetMessage;
import com.game.pet.handler.ReqGotPetHandler;
import com.game.pet.message.ReqHTCDClearMessage;
import com.game.pet.handler.ReqHTCDClearHandler;
import com.game.activities.message.ReqReceiveLiJinGiftMessage;
import com.game.activities.handler.ReqReceiveLiJinGiftHandler;
import com.game.country.message.ResCountrySiegeSelectToGameMessage;
import com.game.country.handler.ResCountrySiegeSelectToGameHandler;
import com.game.country.message.ReqCountryWarCarToGameMessage;
import com.game.country.handler.ReqCountryWarCarToGameHandler;
import com.game.country.message.ReqCountryStructureInfoToGameMessage;
import com.game.country.handler.ReqCountryStructureInfoToGameHandler;
import com.game.country.message.ReqCountrysalaryToGameMessage;
import com.game.country.handler.ReqCountrysalaryToGameHandler;
import com.game.toplist.message.ReqRecieveChestToServerMessage;
import com.game.toplist.handler.ReqRecieveChestToServerHandler;
import com.game.backpack.message.ReqOpenTimeCellMessage;
import com.game.backpack.handler.ReqOpenTimeCellHandler;
import com.game.country.message.ReqKingCityChestSelectToGameMessage;
import com.game.country.handler.ReqKingCityChestSelectToGameHandler;
import com.game.vip.message.ReqReceiveVIPRewardMessage;
import com.game.vip.handler.ReqReceiveVIPRewardHandler;
import com.game.vip.message.ReqPlayerVIPInfoMessage;
import com.game.vip.handler.ReqPlayerVIPInfoHandler;
import com.game.country.message.ResCountrySyncKingCityToGameMessage;
import com.game.country.handler.ResCountrySyncKingCityToGameHandler;
import com.game.map.message.ReqMonsterInfoMessage;
import com.game.map.handler.ReqMonsterInfoHandler;
import com.game.vip.message.ReqReceiveVIPTopRewardMessage;
import com.game.vip.handler.ReqReceiveVIPTopRewardHandler;
import com.game.card.message.ReqCardPhoneToServerMessage;
import com.game.card.handler.ReqCardPhoneToServerHandler;
import com.game.scripts.message.ReqScriptToGameMessage;
import com.game.scripts.handler.ReqScriptToGameHandler;
import com.game.scripts.message.ReqScriptExcuteMessage;
import com.game.scripts.handler.ReqScriptExcuteHandler;
import com.game.zones.message.ReqZoneContinuousRaidsMessage;
import com.game.zones.handler.ReqZoneContinuousRaidsHandler;
import com.game.zones.message.ReqZoneContinuousRaidsYBMessage;
import com.game.zones.handler.ReqZoneContinuousRaidsYBHandler;
import com.game.zones.message.ReqZoneContinuousRaidsStopMessage;
import com.game.zones.handler.ReqZoneContinuousRaidsStopHandler;
import com.game.gem.message.ReqGemUseStrengthenMessage;
import com.game.gem.handler.ReqGemUseStrengthenHandler;
import com.game.zones.message.ReqZoneTeamEnterToGameMessage;
import com.game.zones.handler.ReqZoneTeamEnterToGameHandler;
import com.game.zones.message.ReqZoneTeamSelectToGameMessage;
import com.game.zones.handler.ReqZoneTeamSelectToGameHandler;
import com.game.zones.message.ReqZoneTeamOpenToGameMessage;
import com.game.zones.handler.ReqZoneTeamOpenToGameHandler;
import com.game.country.message.ReqCountryWarCarInAdvanceToGameMessage;
import com.game.country.handler.ReqCountryWarCarInAdvanceToGameHandler;
import com.game.task.message.ReqDailyTaskTransMessage;
import com.game.task.handler.ReqDailyTaskTransHandler;
import com.game.task.message.ReqConqueryTaskTransMessage;
import com.game.task.handler.ReqConqueryTaskTransHandler;
import com.game.guildflag.message.ReqOpenGuildFlagToGameMessage;
import com.game.guildflag.handler.ReqOpenGuildFlagToGameHandler;
import com.game.guildflag.message.ReqInsertGuildFlagToGameMessage;
import com.game.guildflag.handler.ReqInsertGuildFlagToGameHandler;
import com.game.offline.message.ReqRetreatInfoMessage;
import com.game.offline.handler.ReqRetreatInfoHandler;
import com.game.offline.message.ReqGetRetreatAwardMessage;
import com.game.offline.handler.ReqGetRetreatAwardHandler;
import com.game.task.message.ReqTreasureHuntTaskTransMessage;
import com.game.task.handler.ReqTreasureHuntTaskTransHandler;
import com.game.task.message.ReqConquerTaskQuckFinshMessage;
import com.game.task.handler.ReqConquerTaskQuckFinshHandler;
import com.game.arrow.message.ReqArrowInfoOpenMessage;
import com.game.arrow.handler.ReqArrowInfoOpenHandler;
import com.game.arrow.message.ReqStarActivationMessage;
import com.game.arrow.handler.ReqStarActivationHandler;
import com.game.arrow.message.ReqBowActivationMessage;
import com.game.arrow.handler.ReqBowActivationHandler;
import com.game.zones.message.ReqZoneAutoAwardToGameMessage;
import com.game.zones.handler.ReqZoneAutoAwardToGameHandler;
import com.game.task.message.ReqRankTaskQuckFinshMessage;
import com.game.task.handler.ReqRankTaskQuckFinshHandler;
import com.game.signwage.message.ReqSignToClientMessage;
import com.game.signwage.handler.ReqSignToClientHandler;
import com.game.signwage.message.ReqReceiveSalaryToClientMessage;
import com.game.signwage.handler.ReqReceiveSalaryToClientHandler;
import com.game.signwage.message.ReqReceiveAwardsToClientMessage;
import com.game.signwage.handler.ReqReceiveAwardsToClientHandler;
import com.game.signwage.message.ReqWageToClientMessage;
import com.game.signwage.handler.ReqWageToClientHandler;
import com.game.signwage.message.ReqWageERNIEToClientMessage;
import com.game.signwage.handler.ReqWageERNIEToClientHandler;
import com.game.signwage.message.ReqClickSignToClientMessage;
import com.game.signwage.handler.ReqClickSignToClientHandler;
import com.game.signwage.message.ReqReceiveBeautyMessage;
import com.game.signwage.handler.ReqReceiveBeautyHandler;
import com.game.signwage.message.ReqOpenReceiveBeautyMessage;
import com.game.signwage.handler.ReqOpenReceiveBeautyHandler;
import com.game.arrow.message.ReqFightSpiritOpenMessage;
import com.game.arrow.handler.ReqFightSpiritOpenHandler;
import com.game.arrow.message.ReqFightSpiritGetMessage;
import com.game.arrow.handler.ReqFightSpiritGetHandler;
import com.game.gm.message.GmCommandToServerMessage;
import com.game.gm.handler.GmCommandToServerHandler;
import com.game.chat.message.ReqLoadBlackListWSMessage;
import com.game.chat.handler.ReqLoadBlackListWSHandler;
import com.game.monster.message.ReqMonsterDoubleTimeToGameMessage;
import com.game.monster.handler.ReqMonsterDoubleTimeToGameHandler;
import com.game.task.message.ReqRankTaskQuckFinshAllMessage;
import com.game.task.handler.ReqRankTaskQuckFinshAllHandler;
import com.game.spirittree.message.ResActivityReturnFruitToGameMessage;
import com.game.spirittree.handler.ResActivityReturnFruitToGameHandler;
import com.game.spirittree.message.ReqContinuousRipeningToGameMessage;
import com.game.spirittree.handler.ReqContinuousRipeningToGameHandler;
import com.game.player.message.ReqVipPlayerChangeMapToServerMessage;
import com.game.player.handler.ReqVipPlayerChangeMapToServerHandler;
import com.game.collect.message.ReqSubmitFragByTypeMessage;
import com.game.collect.handler.ReqSubmitFragByTypeHandler;
import com.game.collect.message.ReqSubmitFragMessage;
import com.game.collect.handler.ReqSubmitFragHandler;
import com.game.melting.message.ReqMeltingItemToServerMessage;
import com.game.melting.handler.ReqMeltingItemToServerHandler;
import com.game.horseweapon.message.ReqGetHorseWeaponInfoMessage;
import com.game.horseweapon.handler.ReqGetHorseWeaponInfoHandler;
import com.game.horseweapon.message.ReqWearHorseWeaponStateMessage;
import com.game.horseweapon.handler.ReqWearHorseWeaponStateHandler;
import com.game.horseweapon.message.ReqHorseWeaponStageUpPanelMessage;
import com.game.horseweapon.handler.ReqHorseWeaponStageUpPanelHandler;
import com.game.horseweapon.message.ReqHorseWeaponStageUpStartMessage;
import com.game.horseweapon.handler.ReqHorseWeaponStageUpStartHandler;
import com.game.zones.message.ReqZoneImmediatelyByCostMessage;
import com.game.zones.handler.ReqZoneImmediatelyByCostHandler;
import com.game.horseweapon.message.ReqSetHorseWeaponSkillMessage;
import com.game.horseweapon.handler.ReqSetHorseWeaponSkillHandler;
import com.game.chestbox.message.ReqChestBoxShowPanelToServerMessage;
import com.game.chestbox.handler.ReqChestBoxShowPanelToServerHandler;
import com.game.chestbox.message.ReqChestBoxOpenToServerMessage;
import com.game.chestbox.handler.ReqChestBoxOpenToServerHandler;
import com.game.chestbox.message.ReqChestBoxGetGridItemToServerMessage;
import com.game.chestbox.handler.ReqChestBoxGetGridItemToServerHandler;
import com.game.chestbox.message.ReqChestBoxAutoSetToServerMessage;
import com.game.chestbox.handler.ReqChestBoxAutoSetToServerHandler;
import com.game.server.message.ReqRegisterGameForPublicMessage;
import com.game.server.handler.ReqRegisterGameForPublicHandler;
import com.game.server.message.ResRegisterGameForPublicMessage;
import com.game.server.handler.ResRegisterGameForPublicHandler;
import com.game.gift.message.ReqGetPlatformGiftMessage;
import com.game.gift.handler.ReqGetPlatformGiftHandler;
import com.game.gift.message.ReqPlatformGiftListMessage;
import com.game.gift.handler.ReqPlatformGiftListHandler;
import com.game.server.message.ReqCheckToGameMessage;
import com.game.server.handler.ReqCheckToGameHandler;
import com.game.biwudao.message.ReqBiWuDaoSelectToGameMessage;
import com.game.biwudao.handler.ReqBiWuDaoSelectToGameHandler;
import com.game.task.message.ReqTaskGoldAddNumMessage;
import com.game.task.handler.ReqTaskGoldAddNumHandler;
import com.game.dataserver.message.ReqSyncPlayerToDataServerMessage;
import com.game.dataserver.handler.ReqSyncPlayerToDataServerHandler;
import com.game.dataserver.message.ReqChangeServerMessage;
import com.game.dataserver.handler.ReqChangeServerHandler;
import com.game.dataserver.message.ResSyncPlayerToDataServerMessage;
import com.game.dataserver.handler.ResSyncPlayerToDataServerHandler;
import com.game.zones.message.ReqZoneCancelSignupToGameMessage;
import com.game.zones.handler.ReqZoneCancelSignupToGameHandler;
import com.game.gift.message.ReqStartShuffleRaffleMessage;
import com.game.gift.handler.ReqStartShuffleRaffleHandler;
import com.game.player.message.ReqReportPlayerSpeedMessage;
import com.game.player.handler.ReqReportPlayerSpeedHandler;
import com.game.login.message.ReqJustCreateCharacterToGameMessage;
import com.game.login.handler.ReqJustCreateCharacterToGameHandler;
import com.game.dataserver.message.ReqSyncPlayerInfoFromDataServerMessage;
import com.game.dataserver.handler.ReqSyncPlayerInfoFromDataServerHandler;
import com.game.dataserver.message.ResSyncPlayerInfoFromDataServerMessage;
import com.game.dataserver.handler.ResSyncPlayerInfoFromDataServerHandler;
import com.game.dataserver.message.ReqPlayerStateFromDataServerMessage;
import com.game.dataserver.handler.ReqPlayerStateFromDataServerHandler;
import com.game.dataserver.message.ResPlayerStateFromDataServerMessage;
import com.game.dataserver.handler.ResPlayerStateFromDataServerHandler;
import com.game.dataserver.message.ReqPlayerQuitToDataServerMessage;
import com.game.dataserver.handler.ReqPlayerQuitToDataServerHandler;
import com.game.dataserver.message.ResPlayerQuitToDataServerMessage;
import com.game.dataserver.handler.ResPlayerQuitToDataServerHandler;
import com.game.publogin.message.ReqLoginCharacterToPublicGameMessage;
import com.game.publogin.handler.ReqLoginCharacterToPublicGameHandler;
import com.game.publogin.message.ReqQuitToPublicGameMessage;
import com.game.publogin.handler.ReqQuitToPublicGameHandler;
import com.game.realm.message.ReqBreakthroughToGameMessage;
import com.game.realm.handler.ReqBreakthroughToGameHandler;
import com.game.realm.message.ReqIntensifyToGameMessage;
import com.game.realm.handler.ReqIntensifyToGameHandler;
import com.game.wine.message.ReqWineShowPanelMessage;
import com.game.wine.handler.ReqWineShowPanelHandler;
import com.game.wine.message.ReqWineRandomMessage;
import com.game.wine.handler.ReqWineRandomHandler;
import com.game.wine.message.ReqWineMoneyChangeMessage;
import com.game.wine.handler.ReqWineMoneyChangeHandler;
import com.game.wine.message.ReqWineGoldChangeMessage;
import com.game.wine.handler.ReqWineGoldChangeHandler;
import com.game.wine.message.ReqWineGetPrizeMessage;
import com.game.wine.handler.ReqWineGetPrizeHandler;
import com.game.country.message.ReqCountryOpenTopToGameMessage;
import com.game.country.handler.ReqCountryOpenTopToGameHandler;
import com.game.guild.message.ResFriendGuildListToGameMessage;
import com.game.guild.handler.ResFriendGuildListToGameHandler;
import com.game.guild.message.ResFriendGuildToGameMessage;
import com.game.guild.handler.ResFriendGuildToGameHandler;
import com.game.dataserver.message.ReqSyncPlayerCrossToDataServerMessage;
import com.game.dataserver.handler.ReqSyncPlayerCrossToDataServerHandler;
import com.game.dataserver.message.ResSyncPlayerCrossToDataServerMessage;
import com.game.dataserver.handler.ResSyncPlayerCrossToDataServerHandler;
import com.game.dataserver.message.ReqPlayerCrossFromDataServerMessage;
import com.game.dataserver.handler.ReqPlayerCrossFromDataServerHandler;
import com.game.dataserver.message.ResPlayerCrossFromDataServerMessage;
import com.game.dataserver.handler.ResPlayerCrossFromDataServerHandler;
import com.game.dataserver.message.ResPlayerCrossFromDataServerErrorMessage;
import com.game.dataserver.handler.ResPlayerCrossFromDataServerErrorHandler;
import com.game.dataserver.message.ReqKickPlayerToCrossServerMessage;
import com.game.dataserver.handler.ReqKickPlayerToCrossServerHandler;
import com.game.dataserver.message.ResSyncPlayerInfoFromDataServerErrorMessage;
import com.game.dataserver.handler.ResSyncPlayerInfoFromDataServerErrorHandler;
import com.game.bag.message.ReqBagSynMessage;
import com.game.bag.handler.ReqBagSynHandler;
import com.game.bag.message.ReqBagItemMoveMessage;
import com.game.bag.handler.ReqBagItemMoveHandler;
import com.game.bag.message.ReqBagItemMoveInMessage;
import com.game.bag.handler.ReqBagItemMoveInHandler;
import com.game.bag.message.ReqBagItemMoveOutMessage;
import com.game.bag.handler.ReqBagItemMoveOutHandler;
import com.game.systemgrant.message.ResSystemgrantRefreshToGameMessage;
import com.game.systemgrant.handler.ResSystemgrantRefreshToGameHandler;
import com.game.hiddenweapon.message.ReqGetHiddenWeaponInfoMessage;
import com.game.hiddenweapon.handler.ReqGetHiddenWeaponInfoHandler;
import com.game.hiddenweapon.message.ReqWearHiddenWeaponStateMessage;
import com.game.hiddenweapon.handler.ReqWearHiddenWeaponStateHandler;
import com.game.hiddenweapon.message.ReqHiddenWeaponStageUpPanelMessage;
import com.game.hiddenweapon.handler.ReqHiddenWeaponStageUpPanelHandler;
import com.game.hiddenweapon.message.ReqHiddenWeaponStageUpStartMessage;
import com.game.hiddenweapon.handler.ReqHiddenWeaponStageUpStartHandler;
import com.game.marriage.message.ReqLaunchProposeToGameMessage;
import com.game.marriage.handler.ReqLaunchProposeToGameHandler;
import com.game.marriage.message.ReqLaunchProposeStartToGameMessage;
import com.game.marriage.handler.ReqLaunchProposeStartToGameHandler;
import com.game.marriage.message.ReqProposeSelectToGameMessage;
import com.game.marriage.handler.ReqProposeSelectToGameHandler;
import com.game.marriage.message.ReqReplaceRingToGameMessage;
import com.game.marriage.handler.ReqReplaceRingToGameHandler;
import com.game.marriage.message.ReqNewLeaveMsgToGameMessage;
import com.game.marriage.handler.ReqNewLeaveMsgToGameHandler;
import com.game.marriage.message.ReqDivorceToGameMessage;
import com.game.marriage.handler.ReqDivorceToGameHandler;
import com.game.marriage.message.ReqApplyWeddingToGameMessage;
import com.game.marriage.handler.ReqApplyWeddingToGameHandler;
import com.game.marriage.message.ReqDivorceSelectToGameMessage;
import com.game.marriage.handler.ReqDivorceSelectToGameHandler;
import com.game.marriage.message.ReqSpouseInfoToGameMessage;
import com.game.marriage.handler.ReqSpouseInfoToGameHandler;
import com.game.marriage.message.ReqRedEnvelopeToGameMessage;
import com.game.marriage.handler.ReqRedEnvelopeToGameHandler;
import com.game.marriage.message.ReqWeddingListToGameMessage;
import com.game.marriage.handler.ReqWeddingListToGameHandler;
import com.game.marriage.message.ReqWeddingParticipateToGameMessage;
import com.game.marriage.handler.ReqWeddingParticipateToGameHandler;
import com.game.marriage.message.ReqWeddingEatingToGameMessage;
import com.game.marriage.handler.ReqWeddingEatingToGameHandler;
import com.game.marriage.message.ReqReceiveredenvelopeToGameMessage;
import com.game.marriage.handler.ReqReceiveredenvelopeToGameHandler;
import com.game.marriage.message.ReqCockRedenvelopeToGameMessage;
import com.game.marriage.handler.ReqCockRedenvelopeToGameHandler;
import com.game.marriage.message.ReqTeaseSpouseToGameMessage;
import com.game.marriage.handler.ReqTeaseSpouseToGameHandler;
import com.game.marriage.message.ReqGetSpouseOtherToGameMessage;
import com.game.marriage.handler.ReqGetSpouseOtherToGameHandler;
import com.game.marriage.message.ReqSpouseMoveToGameMessage;
import com.game.marriage.handler.ReqSpouseMoveToGameHandler;
import com.game.marriage.message.ReqDeleteLeaveMsgToGameMessage;
import com.game.marriage.handler.ReqDeleteLeaveMsgToGameHandler;
import com.game.marriage.message.ReqChangeRingToGameMessage;
import com.game.marriage.handler.ReqChangeRingToGameHandler;
import com.game.hiddenweapon.message.ReqHiddenWeaponStudySkillMessage;
import com.game.hiddenweapon.handler.ReqHiddenWeaponStudySkillHandler;
import com.game.dazuo.message.ReqCohesionZhenQiMessage;
import com.game.dazuo.handler.ReqCohesionZhenQiHandler;
import com.game.protect.message.ReqSelectIsSetToGameMessage;
import com.game.protect.handler.ReqSelectIsSetToGameHandler;
import com.game.protect.message.ReqPasswordSetToGameMessage;
import com.game.protect.handler.ReqPasswordSetToGameHandler;
import com.game.protect.message.ReqVerificationToGameMessage;
import com.game.protect.handler.ReqVerificationToGameHandler;
import com.game.protect.message.ReqPasswordUnlockToGameMessage;
import com.game.protect.handler.ReqPasswordUnlockToGameHandler;
import com.game.protect.message.ReqModifyPasswordToGameMessage;
import com.game.protect.handler.ReqModifyPasswordToGameHandler;
import com.game.protect.message.ReqForgetPasswordToGameMessage;
import com.game.protect.handler.ReqForgetPasswordToGameHandler;
import com.game.protect.message.ReqBackstageModifyToGameMessage;
import com.game.protect.handler.ReqBackstageModifyToGameHandler;
import com.game.command.Handler;
import com.game.message.Message;

/** 
 * @author Commuication Auto Maker
 * 
 * @version 1.0.0
 * 
 * 引用类列表
 */
public class MessagePool {
	//消息类字典
	HashMap<Integer, Class<?>> messages = new HashMap<Integer, Class<?>>();
	//处理类字典
	HashMap<Integer, Class<?>> handlers = new HashMap<Integer, Class<?>>();
	
	public MessagePool(){
		register(105201, BuyItemMessage.class, BuyItemHandler.class);
		register(105202, SellItemMessage.class, SellItemHandler.class);
		register(106201, WearEquipMessage.class, WearEquipHandler.class);
		register(106202, UnwearEquipMessage.class, UnwearEquipHandler.class);
		register(107201, StudySkillMessage.class, StudySkillHandler.class);
		register(107202, LevelUpSkillMessage.class, LevelUpSkillHandler.class);
		register(108201, AddShortCutMessage.class, AddShortCutHandler.class);
		register(108202, RemoveShortCutMessage.class, RemoveShortCutHandler.class);
		register(200201, GmCommandMessage.class, GmCommandHandler.class);
		register(201201, LogInfoMessage.class, LogInfoHandler.class);
		register(107203, SetDefaultSkillMessage.class, SetDefaultSkillHandler.class);
		register(111201, ChatRequestMessage.class, ChatRequestHandler.class);
		register(105203, ReqNotSaleMessage.class, ReqNotSaleHandler.class);
		register(108203, MoveShortCutMessage.class, MoveShortCutHandler.class);
		register(105205, ReqRebuyListMessage.class, ReqRebuyListHandler.class);
		register(105204, ReqRebuyMessage.class, ReqRebuyHandler.class);
		register(113201, ReqRemoveBuffMessage.class, ReqRemoveBuffHandler.class);
		register(113202, ReqBuffInfoMessage.class, ReqBuffInfoHandler.class);
		register(107204, ReqCompleteMomentMessage.class, ReqCompleteMomentHandler.class);
		register(107205, NowLearnSkillQueryMessage.class, NowLearnSkillQueryHandler.class);
		register(111202, RoleQueryMessage.class, RoleQueryHandler.class);
		register(300302, ResRegisterGateMessage.class, ResRegisterGateHandler.class);
		register(300304, ResRegisterWorldMessage.class, ResRegisterWorldHandler.class);
		register(100301, ReqLoginCharacterToGameMessage.class, ReqLoginCharacterToGameHandler.class);
		register(100304, ReqCreateCharacterToGameMessage.class, ReqCreateCharacterToGameHandler.class);
		register(100204, ReqLoadFinishMessage.class, ReqLoadFinishHandler.class);
		register(100305, ReqQuitToGameMessage.class, ReqQuitToGameHandler.class);
		register(116201, GetDianjiangchunInfoToServerMessage.class, GetDianjiangchunInfoToServerHandler.class);
		register(116202, GetBeginDianjiangchunToServerMessage.class, GetBeginDianjiangchunToServerHandler.class);
		register(116203, GetChangeLuckToServerMessage.class, GetChangeLuckToServerHandler.class);
		register(116204, GetReceiveintinfuriatingvalueToServerMessage.class, GetReceiveintinfuriatingvalueToServerHandler.class);
		register(118201, ReqCreateateamGameMessage.class, ReqCreateateamGameHandler.class);
		register(118202, ReqApplyGameMessage.class, ReqApplyGameHandler.class);
		register(118203, ReqApplyGameSelectMessage.class, ReqApplyGameSelectHandler.class);
		register(118204, ReqInviteGameMessage.class, ReqInviteGameHandler.class);
		register(118205, ReqInviteGameSelectMessage.class, ReqInviteGameSelectHandler.class);
		register(118206, ReqToleaveGameMessage.class, ReqToleaveGameHandler.class);
		register(118207, ReqAppointGameMessage.class, ReqAppointGameHandler.class);
		register(118208, ReqAppointGameSelectMessage.class, ReqAppointGameSelectHandler.class);
		register(118209, ReqAutoTeaminvitedGameMessage.class, ReqAutoTeaminvitedGameHandler.class);
		register(118210, ReqAutoIntoTeamApplyGameMessage.class, ReqAutoIntoTeamApplyGameHandler.class);
		register(118302, ResTeamGameMessage.class, ResTeamGameHandler.class);
		register(118310, ResToleaveWorldMessage.class, ResToleaveWorldHandler.class);
		register(101201, ReqRunningMessage.class, ReqRunningHandler.class);
		register(101202, ReqJumpMessage.class, ReqJumpHandler.class);
		register(101203, ReqStartBlockMessage.class, ReqStartBlockHandler.class);
		register(101204, ReqStopBlockMessage.class, ReqStopBlockHandler.class);
		register(101205, ReqPlayerStopMessage.class, ReqPlayerStopHandler.class);
		register(101206, ReqChangeMapByMoveMessage.class, ReqChangeMapByMoveHandler.class);
		register(101208, ReqEnterMapMessage.class, ReqEnterMapHandler.class);
		register(118211, ReqUpdateTeaminfoGameMessage.class, ReqUpdateTeaminfoGameHandler.class);
		register(119201, ReqRelationGetListToServerMessage.class, ReqRelationGetListToServerHandler.class);
		register(119202, ReqRelationAddToServerMessage.class, ReqRelationAddToServerHandler.class);
		register(119203, ReqRelationDeleteToServerMessage.class, ReqRelationDeleteToServerHandler.class);
		register(119204, ReqRelationSortToServerMessage.class, ReqRelationSortToServerHandler.class);
		register(119205, ReqRelationMoodToServerMessage.class, ReqRelationMoodToServerHandler.class);
		register(104201, ReqGetItemsMessage.class, ReqGetItemsHandler.class);
		register(104202, ReqMoveItemMessage.class, ReqMoveItemHandler.class);
		register(104203, ReqUseItemMessage.class, ReqUseItemHandler.class);
		register(104204, ReqDelItemMessage.class, ReqDelItemHandler.class);
		register(104205, ReqClearUpGoodsMessage.class, ReqClearUpGoodsHandler.class);
		register(104207, ReqOpenCellMessage.class, ReqOpenCellHandler.class);
		register(104208, ReqCellTimeQueryMessage.class, ReqCellTimeQueryHandler.class);
		register(104209, ReqDiscardMessage.class, ReqDiscardHandler.class);
		register(104210, ReqDestroyMessage.class, ReqDestroyHandler.class);
		register(112200, ReqStoreGetItemsMessage.class, ReqStoreGetItemsHandler.class);
		register(112201, ReqStoreMoveItemMessage.class, ReqStoreMoveItemHandler.class);
		register(112202, ReqStoreClearUpMessage.class, ReqStoreClearUpHandler.class);
		register(112203, ReqStoreOpenCellMessage.class, ReqStoreOpenCellHandler.class);
		register(112204, ReqStoreCellTimeQueryMessage.class, ReqStoreCellTimeQueryHandler.class);
		register(112206, ReqBagToStoreMessage.class, ReqBagToStoreHandler.class);
		register(112207, ReqStoreToBagMessage.class, ReqStoreToBagHandler.class);
		register(122201, ReqTransactionsLaunchMessage.class, ReqTransactionsLaunchHandler.class);
		register(122202, ReqTransactionsAcceptMessage.class, ReqTransactionsAcceptHandler.class);
		register(122203, ReqTransactionsRefuseMessage.class, ReqTransactionsRefuseHandler.class);
		register(122204, ReqTransactionsCanceledMessage.class, ReqTransactionsCanceledHandler.class);
		register(122205, ReqTransactionsIntoItemMessage.class, ReqTransactionsIntoItemHandler.class);
		register(122206, ReqTransactionsRemoveItemMessage.class, ReqTransactionsRemoveItemHandler.class);
		register(122207, ReqTransactionsChangeGoldMessage.class, ReqTransactionsChangeGoldHandler.class);
		register(122208, ReqTransactionsChangeYuanbaoMessage.class, ReqTransactionsChangeYuanbaoHandler.class);
		register(122209, ReqTransactionsSetStateMessage.class, ReqTransactionsSetStateHandler.class);
		register(122210, ReqCanreceiveYuanbaoMessage.class, ReqCanreceiveYuanbaoHandler.class);
		register(122211, ReqAutorefusaldealMessage.class, ReqAutorefusaldealHandler.class);
		register(102201, ReqAttackMonsterMessage.class, ReqAttackMonsterHandler.class);
		register(102202, ReqAttackPlayerMessage.class, ReqAttackPlayerHandler.class);
		register(120201, ReqTaskReceiveMessage.class, ReqTaskReceiveHandler.class);
		register(120202, ReqTaskFinshMessage.class, ReqTaskFinshHandler.class);
		register(120203, ReqTaskUpAchieveMessage.class, ReqTaskUpAchieveHandler.class);
		register(120204, ReqTaskDownHardMessage.class, ReqTaskDownHardHandler.class);
		register(120205, ReqReceiveRewardsMessage.class, ReqReceiveRewardsHandler.class);
		register(120206, ReqQuickFinshMessage.class, ReqQuickFinshHandler.class);
		register(101301, ReqLoadFinishForChangeMapToGameMessage.class, ReqLoadFinishForChangeMapToGameHandler.class);
		register(104211, ReqTakeUpMessage.class, ReqTakeUpHandler.class);
		register(121201, ReqGuildCreateToServerMessage.class, ReqGuildCreateToServerHandler.class);
		register(121202, ReqGuildAutoArgeeAddGuildToServerMessage.class, ReqGuildAutoArgeeAddGuildToServerHandler.class);
		register(121203, ReqGuildGetGuildListToServerMessage.class, ReqGuildGetGuildListToServerHandler.class);
		register(121204, ReqGuildApplyAddToServerMessage.class, ReqGuildApplyAddToServerHandler.class);
		register(121205, ReqGuildInviteAddToServerMessage.class, ReqGuildInviteAddToServerHandler.class);
		register(121206, ReqGuildGetMemberListToServerMessage.class, ReqGuildGetMemberListToServerHandler.class);
		register(121207, ReqGuildAddMemberToServerMessage.class, ReqGuildAddMemberToServerHandler.class);
		register(121208, ReqGuildQuitToServerMessage.class, ReqGuildQuitToServerHandler.class);
		register(121209, ReqGuildChangeNickNameToServerMessage.class, ReqGuildChangeNickNameToServerHandler.class);
		register(121210, ReqGuildChangePowerLevelToServerMessage.class, ReqGuildChangePowerLevelToServerHandler.class);
		register(121211, ReqGuildDeleteMemberToServerMessage.class, ReqGuildDeleteMemberToServerHandler.class);
		register(121212, ReqGuildAutoGuildArgeeAddToServerMessage.class, ReqGuildAutoGuildArgeeAddToServerHandler.class);
		register(121213, ReqGuildChangeBulletinToServerMessage.class, ReqGuildChangeBulletinToServerHandler.class);
		register(121214, ReqGuildSubmitItemToServerMessage.class, ReqGuildSubmitItemToServerHandler.class);
		register(121215, ReqGuildChangeBannerIconToServerMessage.class, ReqGuildChangeBannerIconToServerHandler.class);
		register(121216, ReqGuildChangeBannerNameToServerMessage.class, ReqGuildChangeBannerNameToServerHandler.class);
		register(121217, ReqGuildBannerLevelUpToServerMessage.class, ReqGuildBannerLevelUpToServerHandler.class);
		register(121218, ReqGuildAddDiplomaticToServerMessage.class, ReqGuildAddDiplomaticToServerHandler.class);
		register(121219, ReqGuildDeleteDiplomaticToServerMessage.class, ReqGuildDeleteDiplomaticToServerHandler.class);
		register(121220, ReqGuildDeleteGuildToServerMessage.class, ReqGuildDeleteGuildToServerHandler.class);
		register(121221, ReqGuildGetEventListToServerMessage.class, ReqGuildGetEventListToServerHandler.class);
		register(121380, ResInnerGuildAloneGuildInfoToServerMessage.class, ResInnerGuildAloneGuildInfoToServerHandler.class);
		register(121381, ResInnerGuildAloneMemberInfoToServerMessage.class, ResInnerGuildAloneMemberInfoToServerHandler.class);
		register(103201, ReqReviveMessage.class, ReqReviveHandler.class);
		register(103202, ReqLocalReviveMessage.class, ReqLocalReviveHandler.class);
		register(103203, ReqOtherPlayerInfoMessage.class, ReqOtherPlayerInfoHandler.class);
		register(103204, ReqChangePKStateMessage.class, ReqChangePKStateHandler.class);
		register(103205, ReqAutoStartMessage.class, ReqAutoStartHandler.class);
		register(103206, ReqAutoEndMessage.class, ReqAutoEndHandler.class);
		register(118212, ReqMapSearchTeamInfoGameMessage.class, ReqMapSearchTeamInfoGameHandler.class);
		register(118213, ReqMapSearchPlayerInfoGameMessage.class, ReqMapSearchPlayerInfoGameHandler.class);
		register(101209, ReqNpcTransMessage.class, ReqNpcTransHandler.class);
		register(120207, ReqTaskInfoMationMessage.class, ReqTaskInfoMationHandler.class);
		register(120208, ReqConquerTaskDevourMessage.class, ReqConquerTaskDevourHandler.class);
		register(123201, ReqStallsOpenUpMessage.class, ReqStallsOpenUpHandler.class);
		register(123202, ReqStallsPlayerIdLookMessage.class, ReqStallsPlayerIdLookHandler.class);
		register(123203, ReqStallsSortMessage.class, ReqStallsSortHandler.class);
		register(123204, ReqStallsBuyMessage.class, ReqStallsBuyHandler.class);
		register(123205, ReqStallsProductWasAddedMessage.class, ReqStallsProductWasAddedHandler.class);
		register(123206, ReqStallsAdjustPricesMessage.class, ReqStallsAdjustPricesHandler.class);
		register(123207, ReqStallsOffShelfMessage.class, ReqStallsOffShelfHandler.class);
		register(123208, ReqStallsSearchMessage.class, ReqStallsSearchHandler.class);
		register(123209, ReqStallsLooklogMessage.class, ReqStallsLooklogHandler.class);
		register(123211, ReqChangeStallsNameMessage.class, ReqChangeStallsNameHandler.class);
		register(114302, ResMonsterSyncMessage.class, ResMonsterSyncHandler.class);
		register(124151, ReqMailQueryListToServerMessage.class, ReqMailQueryListToServerHandler.class);
		register(124152, ReqMailQueryDetailToServerMessage.class, ReqMailQueryDetailToServerHandler.class);
		register(124153, ReqMailGetItemToServerMessage.class, ReqMailGetItemToServerHandler.class);
		register(124154, ReqMailSendNewMailToServerMessage.class, ReqMailSendNewMailToServerHandler.class);
		register(124155, ReqMailDeleteMailToServerMessage.class, ReqMailDeleteMailToServerHandler.class);
		register(124156, ReqMailQueryUserToServerMessage.class, ReqMailQueryUserToServerHandler.class);
		register(124157, ReqMailReturnToServerMessage.class, ReqMailReturnToServerHandler.class);
		register(122212, ReqOpenTmpYuanbaoPanelMessage.class, ReqOpenTmpYuanbaoPanelHandler.class);
		register(122213, ReqGetTmpYuanbaoMessage.class, ReqGetTmpYuanbaoHandler.class);
		register(123305, ResStallsBuycheckToGameMessage.class, ResStallsBuycheckToGameHandler.class);
		register(123307, ResStallsBuyDeductingToGameMessage.class, ResStallsBuyDeductingToGameHandler.class);
		register(123308, ResStallsBuyAddMoneyToGameMessage.class, ResStallsBuyAddMoneyToGameHandler.class);
		register(123309, ResStallsBuyDeductingFailToGameMessage.class, ResStallsBuyDeductingFailToGameHandler.class);
		register(123311, ResStallsProductWasAddedFailToGameMessage.class, ResStallsProductWasAddedFailToGameHandler.class);
		register(123315, ResStallsOffShelfToGameMessage.class, ResStallsOffShelfToGameHandler.class);
		register(100308, ResPlayerWorldInfoMessage.class, ResPlayerWorldInfoHandler.class);
		register(115201, ReqLongYuanOpenMessage.class, ReqLongYuanOpenHandler.class);
		register(115202, ReqLongYuanActivationMessage.class, ReqLongYuanActivationHandler.class);
		register(115203, ReqLongYuanTipsMessage.class, ReqLongYuanTipsHandler.class);
		register(115204, ReqLongYuanStarMapTipsMessage.class, ReqLongYuanStarMapTipsHandler.class);
		register(103308, ReqOtherPlayerInfoToGameMessage.class, ReqOtherPlayerInfoToGameHandler.class);
		register(100310, ResPlayerNonageToGameMessage.class, ResPlayerNonageToGameHandler.class);
		register(103207, ReqNonageTimeMessage.class, ReqNonageTimeHandler.class);
		register(119320, ResInnerRelationSendListToWorldMessage.class, ResInnerRelationSendListToWorldHandler.class);
		register(103208, ReqPlayerNonageRegisterMessage.class, ReqPlayerNonageRegisterHandler.class);
		register(118214, ReqMapSearchMemberNameGameMessage.class, ReqMapSearchMemberNameGameHandler.class);
		register(118215, ReqGenericSearchToGameMessage.class, ReqGenericSearchToGameHandler.class);
		register(119206, ReqRelationConfigToServerMessage.class, ReqRelationConfigToServerHandler.class);
		register(125201, ReqGetMenuStatusMessage.class, ReqGetMenuStatusHandler.class);
		register(125202, ReqSetMenuStatusMessage.class, ReqSetMenuStatusHandler.class);
		register(126201, ReqGethorseInfoMessage.class, ReqGethorseInfoHandler.class);
		register(126202, ReqChangeRidingStateMessage.class, ReqChangeRidingStateHandler.class);
		register(126203, ReqhorseStageUpPanelMessage.class, ReqhorseStageUpPanelHandler.class);
		register(126204, ReqhorseStageUpStartMessage.class, ReqhorseStageUpStartHandler.class);
		register(126205, ReqhorseLuckyRodMessage.class, ReqhorseLuckyRodHandler.class);
		register(126206, ReqhorseLuckyPenteMessage.class, ReqhorseLuckyPenteHandler.class);
		register(126207, ReqhorseReceiveMessage.class, ReqhorseReceiveHandler.class);
		register(126208, ReqhorseClearCDMessage.class, ReqhorseClearCDHandler.class);
		register(101210, ReqGoldMapTransMessage.class, ReqGoldMapTransHandler.class);
		register(127101, ReqFightPowerToServerMessage.class, ReqFightPowerToServerHandler.class);
		register(128201, ReqZonePanelSelectMessage.class, ReqZonePanelSelectHandler.class);
		register(128202, ReqZoneIntoMessage.class, ReqZoneIntoHandler.class);
		register(128204, ReqZoneOutMessage.class, ReqZoneOutHandler.class);
		register(126209, ReqOpenSkillUpPanelMessage.class, ReqOpenSkillUpPanelHandler.class);
		register(103209, ReqPlayerAvatarChangeMessage.class, ReqPlayerAvatarChangeHandler.class);
		register(119321, ResInnerRelationAddNoticeMessage.class, ResInnerRelationAddNoticeHandler.class);
		register(129201, ReqGetGiftItemsToServerMessage.class, ReqGetGiftItemsToServerHandler.class);
		register(126210, ReqSkillInfoMessage.class, ReqSkillInfoHandler.class);
		register(126211, ReqChangeHorseMessage.class, ReqChangeHorseHandler.class);
		register(130201, ReqStrengItemToServerMessage.class, ReqStrengItemToServerHandler.class);
		register(130202, ReqStageUpItemToServerMessage.class, ReqStageUpItemToServerHandler.class);
		register(130203, ReqStrengClearCoolingMessage.class, ReqStrengClearCoolingHandler.class);
		register(130204, ReqStrengthenStateMessage.class, ReqStrengthenStateHandler.class);
		register(118216, ReqIntoTeamToGameMessage.class, ReqIntoTeamToGameHandler.class);
		register(131201, ReqPlugSetInfoMessage.class, ReqPlugSetInfoHandler.class);
		register(103210, ReqPlayerCheckOnlineMessage.class, ReqPlayerCheckOnlineHandler.class);
		register(103211, ReqGetPlayerAppearanceInfoMessage.class, ReqGetPlayerAppearanceInfoHandler.class);
		register(103314, ReqDelPlayerToGameMessage.class, ReqDelPlayerToGameHandler.class);
		register(101211, ReqGetLinesMessage.class, ReqGetLinesHandler.class);
		register(101212, ReqSelectLineMessage.class, ReqSelectLineHandler.class);
		register(132201, ReqOpenGemPanelMessage.class, ReqOpenGemPanelHandler.class);
		register(132202, ReqGemIntoMessage.class, ReqGemIntoHandler.class);
		register(132203, ReqGemActivationORUpMessage.class, ReqGemActivationORUpHandler.class);
		register(105206, ReqShopListMessage.class, ReqShopListHandler.class);
		register(103316, ResPlayerNameInfoToGameMessage.class, ResPlayerNameInfoToGameHandler.class);
		register(103212, ReqChangePlayerNameMessage.class, ReqChangePlayerNameHandler.class);
		register(103319, ResChangePlayerNameToGameMessage.class, ResChangePlayerNameToGameHandler.class);
		register(134301, RechargeMessage.class, RechargeHandler.class);
		register(118321, ResTeamchangeToGameMessage.class, ResTeamchangeToGameHandler.class);
		register(300307, ReqCloseForGameMessage.class, ReqCloseForGameHandler.class);
		register(135301, ReqPlayerMoneyGoldToGameMessage.class, ReqPlayerMoneyGoldToGameHandler.class);
		register(135302, ReqPlayerInfoToGameMessage.class, ReqPlayerInfoToGameHandler.class);
		register(133201, ReqGetAllFruitInfoToGameMessage.class, ReqGetAllFruitInfoToGameHandler.class);
		register(133202, ReqGetSingleFruitInfoToGameMessage.class, ReqGetSingleFruitInfoToGameHandler.class);
		register(133203, ReqRipeningFruitToGameMessage.class, ReqRipeningFruitToGameHandler.class);
		register(133204, ReqOpenGuildFruitToGameMessage.class, ReqOpenGuildFruitToGameHandler.class);
		register(133303, ResGameMakeFruitInfoMessage.class, ResGameMakeFruitInfoHandler.class);
		register(101213, ReqChangeDirectMessage.class, ReqChangeDirectHandler.class);
		register(133205, ReqGuildFruitOperatingToGameMessage.class, ReqGuildFruitOperatingToGameHandler.class);
		register(133307, ResFruitOperatingToGameMessage.class, ResFruitOperatingToGameHandler.class);
		register(136201, ReqDazuoMessage.class, ReqDazuoHandler.class);
		register(136202, ReqShuangXiuMessage.class, ReqShuangXiuHandler.class);
		register(136203, ReqAgreeShuangXiuMessage.class, ReqAgreeShuangXiuHandler.class);
		register(136204, ReqRefuseShuangXiuMessage.class, ReqRefuseShuangXiuHandler.class);
		register(202302, ResVersionUpdateToGameMessage.class, ResVersionUpdateToGameHandler.class);
		register(137101, ReqCardToServerMessage.class, ReqCardToServerHandler.class);
		register(137301, ResInnerCardToServerMessage.class, ResInnerCardToServerHandler.class);
		register(138201, ReqGetRewardMessage.class, ReqGetRewardHandler.class);
		register(138202, ReqActivitiesInfoMessage.class, ReqActivitiesInfoHandler.class);
		register(133308, ReqRipeningDecYBToGameMessage.class, ReqRipeningDecYBToGameHandler.class);
		register(135305, ReqJinYanMessage.class, ReqJinYanHandler.class);
		register(139201, ReqYBCardToGameMessage.class, ReqYBCardToGameHandler.class);
		register(139302, ResYBCardReceiveToGameMessage.class, ResYBCardReceiveToGameHandler.class);
		register(139303, ResYBCardNoticeToGameMessage.class, ResYBCardNoticeToGameHandler.class);
		register(139304, ResYBCardAddYBPlayerToGameMessage.class, ResYBCardAddYBPlayerToGameHandler.class);
		register(133206, ReqGuildFruitLogToGameMessage.class, ReqGuildFruitLogToGameHandler.class);
		register(135306, ReqChangePlayerCurrencyMessage.class, ReqChangePlayerCurrencyHandler.class);
		register(133311, ResGuildAccExpToWorldMessage.class, ResGuildAccExpToWorldHandler.class);
		register(131202, ReqPlugBackToCityMessage.class, ReqPlugBackToCityHandler.class);
		register(129202, ReqGetOtherGiftItemsToServerMessage.class, ReqGetOtherGiftItemsToServerHandler.class);
		register(105207, ReqSellItemsMessage.class, ReqSellItemsHandler.class);
		register(128205, ReqZoneImmediatelyMessage.class, ReqZoneImmediatelyHandler.class);
		register(128206, ReqZoneOpenPanelMessage.class, ReqZoneOpenPanelHandler.class);
		register(128203, ReqSelectAwardMessage.class, ReqSelectAwardHandler.class);
		register(103213, ReqScriptCommonPlayerToServerMessage.class, ReqScriptCommonPlayerToServerHandler.class);
		register(128207, ReqZoneReceiveawardsMessage.class, ReqZoneReceiveawardsHandler.class);
		register(140201, ReqNpcServicesMessage.class, ReqNpcServicesHandler.class);
		register(140202, ReqServiceMessage.class, ReqServiceHandler.class);
		register(124158, ReqMailListGetItemToServerMessage.class, ReqMailListGetItemToServerHandler.class);
		register(142201, ReqGetTopListToServerMessage.class, ReqGetTopListToServerHandler.class);
		register(142202, ReqWorShipToServerMessage.class, ReqWorShipToServerHandler.class);
		register(142351, ResGetTopAwardToServerMessage.class, ResGetTopAwardToServerHandler.class);
		register(102203, ReqChangeAttackTargetMessage.class, ReqChangeAttackTargetHandler.class);
		register(102204, ReqAttackPetMessage.class, ReqAttackPetHandler.class);
		register(143201, ReqEpalaceDiceToGameMessage.class, ReqEpalaceDiceToGameHandler.class);
		register(143202, ReqEpalaceOpenToGameMessage.class, ReqEpalaceOpenToGameHandler.class);
		register(120112, ResGiveUpTaskMessage.class, ResGiveUpTaskHandler.class);
		register(120209, ReqGiveUpTaskMessage.class, ReqGiveUpTaskHandler.class);
		register(142203, ReqChangeTitleToServerMessage.class, ReqChangeTitleToServerHandler.class);
		register(142352, ResGetTopTitleToServerMessage.class, ResGetTopTitleToServerHandler.class);
		register(143203, ReqEpalaceTaskEndToGameMessage.class, ReqEpalaceTaskEndToGameHandler.class);
		register(143204, ReqEpalaceAbandonTaskToGameMessage.class, ReqEpalaceAbandonTaskToGameHandler.class);
		register(103329, ResScriptCommonServerToServerMessage.class, ResScriptCommonServerToServerHandler.class);
		register(120303, ResTargetMonsterToServerMessage.class, ResTargetMonsterToServerHandler.class);
		register(124201, ResMailSendSystemMailToServerMessage.class, ResMailSendSystemMailToServerHandler.class);
		register(128301, ResfastestClearanceToGameMessage.class, ResfastestClearanceToGameHandler.class);
		register(114201, ReqQueryBossListMessage.class, ReqQueryBossListHandler.class);
		register(114203, ReqQueryBossStateListMessage.class, ReqQueryBossStateListHandler.class);
		register(144201, ReqOpenChallengeToGameMessage.class, ReqOpenChallengeToGameHandler.class);
		register(144202, ReqSelectChallengeToGameMessage.class, ReqSelectChallengeToGameHandler.class);
		register(110201, ReqShowPetMessage.class, ReqShowPetHandler.class);
		register(110202, ReqHiddenPetMessage.class, ReqHiddenPetHandler.class);
		register(110203, ReqPetListQueryMessage.class, ReqPetListQueryHandler.class);
		register(110204, ReqPetHeTiMessage.class, ReqPetHeTiHandler.class);
		register(110205, ReqPetChangeSkillMessage.class, ReqPetChangeSkillHandler.class);
		register(110206, ReqGoldReiveMessage.class, ReqGoldReiveHandler.class);
		register(110207, ReqGotPetMessage.class, ReqGotPetHandler.class);
		register(110208, ReqHTCDClearMessage.class, ReqHTCDClearHandler.class);
		register(138203, ReqReceiveLiJinGiftMessage.class, ReqReceiveLiJinGiftHandler.class);
		register(146201, ResCountrySiegeSelectToGameMessage.class, ResCountrySiegeSelectToGameHandler.class);
		register(146202, ReqCountryWarCarToGameMessage.class, ReqCountryWarCarToGameHandler.class);
		register(146203, ReqCountryStructureInfoToGameMessage.class, ReqCountryStructureInfoToGameHandler.class);
		register(146204, ReqCountrysalaryToGameMessage.class, ReqCountrysalaryToGameHandler.class);
		register(142204, ReqRecieveChestToServerMessage.class, ReqRecieveChestToServerHandler.class);
		register(104213, ReqOpenTimeCellMessage.class, ReqOpenTimeCellHandler.class);
		register(146205, ReqKingCityChestSelectToGameMessage.class, ReqKingCityChestSelectToGameHandler.class);
		register(147201, ReqReceiveVIPRewardMessage.class, ReqReceiveVIPRewardHandler.class);
		register(147202, ReqPlayerVIPInfoMessage.class, ReqPlayerVIPInfoHandler.class);
		register(146302, ResCountrySyncKingCityToGameMessage.class, ResCountrySyncKingCityToGameHandler.class);
		register(101214, ReqMonsterInfoMessage.class, ReqMonsterInfoHandler.class);
		register(147203, ReqReceiveVIPTopRewardMessage.class, ReqReceiveVIPTopRewardHandler.class);
		register(137102, ReqCardPhoneToServerMessage.class, ReqCardPhoneToServerHandler.class);
		register(148302, ReqScriptToGameMessage.class, ReqScriptToGameHandler.class);
		register(148201, ReqScriptExcuteMessage.class, ReqScriptExcuteHandler.class);
		register(128208, ReqZoneContinuousRaidsMessage.class, ReqZoneContinuousRaidsHandler.class);
		register(128209, ReqZoneContinuousRaidsYBMessage.class, ReqZoneContinuousRaidsYBHandler.class);
		register(128210, ReqZoneContinuousRaidsStopMessage.class, ReqZoneContinuousRaidsStopHandler.class);
		register(132204, ReqGemUseStrengthenMessage.class, ReqGemUseStrengthenHandler.class);
		register(128211, ReqZoneTeamEnterToGameMessage.class, ReqZoneTeamEnterToGameHandler.class);
		register(128212, ReqZoneTeamSelectToGameMessage.class, ReqZoneTeamSelectToGameHandler.class);
		register(128213, ReqZoneTeamOpenToGameMessage.class, ReqZoneTeamOpenToGameHandler.class);
		register(146206, ReqCountryWarCarInAdvanceToGameMessage.class, ReqCountryWarCarInAdvanceToGameHandler.class);
		register(120210, ReqDailyTaskTransMessage.class, ReqDailyTaskTransHandler.class);
		register(120211, ReqConqueryTaskTransMessage.class, ReqConqueryTaskTransHandler.class);
		register(149201, ReqOpenGuildFlagToGameMessage.class, ReqOpenGuildFlagToGameHandler.class);
		register(149202, ReqInsertGuildFlagToGameMessage.class, ReqInsertGuildFlagToGameHandler.class);
		register(150201, ReqRetreatInfoMessage.class, ReqRetreatInfoHandler.class);
		register(150202, ReqGetRetreatAwardMessage.class, ReqGetRetreatAwardHandler.class);
		register(120212, ReqTreasureHuntTaskTransMessage.class, ReqTreasureHuntTaskTransHandler.class);
		register(120213, ReqConquerTaskQuckFinshMessage.class, ReqConquerTaskQuckFinshHandler.class);
		register(151201, ReqArrowInfoOpenMessage.class, ReqArrowInfoOpenHandler.class);
		register(151202, ReqStarActivationMessage.class, ReqStarActivationHandler.class);
		register(151203, ReqBowActivationMessage.class, ReqBowActivationHandler.class);
		register(128214, ReqZoneAutoAwardToGameMessage.class, ReqZoneAutoAwardToGameHandler.class);
		register(120214, ReqRankTaskQuckFinshMessage.class, ReqRankTaskQuckFinshHandler.class);
		register(152201, ReqSignToClientMessage.class, ReqSignToClientHandler.class);
		register(152202, ReqReceiveSalaryToClientMessage.class, ReqReceiveSalaryToClientHandler.class);
		register(152203, ReqReceiveAwardsToClientMessage.class, ReqReceiveAwardsToClientHandler.class);
		register(152204, ReqWageToClientMessage.class, ReqWageToClientHandler.class);
		register(152205, ReqWageERNIEToClientMessage.class, ReqWageERNIEToClientHandler.class);
		register(152206, ReqClickSignToClientMessage.class, ReqClickSignToClientHandler.class);
		register(152207, ReqReceiveBeautyMessage.class, ReqReceiveBeautyHandler.class);
		register(152208, ReqOpenReceiveBeautyMessage.class, ReqOpenReceiveBeautyHandler.class);
		register(151204, ReqFightSpiritOpenMessage.class, ReqFightSpiritOpenHandler.class);
		register(151205, ReqFightSpiritGetMessage.class, ReqFightSpiritGetHandler.class);
		register(200303, GmCommandToServerMessage.class, GmCommandToServerHandler.class);
		register(111320, ReqLoadBlackListWSMessage.class, ReqLoadBlackListWSHandler.class);
		register(114304, ReqMonsterDoubleTimeToGameMessage.class, ReqMonsterDoubleTimeToGameHandler.class);
		register(120215, ReqRankTaskQuckFinshAllMessage.class, ReqRankTaskQuckFinshAllHandler.class);
		register(133314, ResActivityReturnFruitToGameMessage.class, ResActivityReturnFruitToGameHandler.class);
		register(133207, ReqContinuousRipeningToGameMessage.class, ReqContinuousRipeningToGameHandler.class);
		register(103214, ReqVipPlayerChangeMapToServerMessage.class, ReqVipPlayerChangeMapToServerHandler.class);
		register(153201, ReqSubmitFragByTypeMessage.class, ReqSubmitFragByTypeHandler.class);
		register(153202, ReqSubmitFragMessage.class, ReqSubmitFragHandler.class);
		register(154201, ReqMeltingItemToServerMessage.class, ReqMeltingItemToServerHandler.class);
		register(155201, ReqGetHorseWeaponInfoMessage.class, ReqGetHorseWeaponInfoHandler.class);
		register(155202, ReqWearHorseWeaponStateMessage.class, ReqWearHorseWeaponStateHandler.class);
		register(155203, ReqHorseWeaponStageUpPanelMessage.class, ReqHorseWeaponStageUpPanelHandler.class);
		register(155204, ReqHorseWeaponStageUpStartMessage.class, ReqHorseWeaponStageUpStartHandler.class);
		register(128215, ReqZoneImmediatelyByCostMessage.class, ReqZoneImmediatelyByCostHandler.class);
		register(155205, ReqSetHorseWeaponSkillMessage.class, ReqSetHorseWeaponSkillHandler.class);
		register(156201, ReqChestBoxShowPanelToServerMessage.class, ReqChestBoxShowPanelToServerHandler.class);
		register(156202, ReqChestBoxOpenToServerMessage.class, ReqChestBoxOpenToServerHandler.class);
		register(156203, ReqChestBoxGetGridItemToServerMessage.class, ReqChestBoxGetGridItemToServerHandler.class);
		register(156204, ReqChestBoxAutoSetToServerMessage.class, ReqChestBoxAutoSetToServerHandler.class);
		register(300311, ReqRegisterGameForPublicMessage.class, ReqRegisterGameForPublicHandler.class);
		register(300312, ResRegisterGameForPublicMessage.class, ResRegisterGameForPublicHandler.class);
		register(129203, ReqGetPlatformGiftMessage.class, ReqGetPlatformGiftHandler.class);
		register(129204, ReqPlatformGiftListMessage.class, ReqPlatformGiftListHandler.class);
		register(300313, ReqCheckToGameMessage.class, ReqCheckToGameHandler.class);
		register(157201, ReqBiWuDaoSelectToGameMessage.class, ReqBiWuDaoSelectToGameHandler.class);
		register(120216, ReqTaskGoldAddNumMessage.class, ReqTaskGoldAddNumHandler.class);
		register(203301, ReqSyncPlayerToDataServerMessage.class, ReqSyncPlayerToDataServerHandler.class);
		register(203201, ReqChangeServerMessage.class, ReqChangeServerHandler.class);
		register(203302, ResSyncPlayerToDataServerMessage.class, ResSyncPlayerToDataServerHandler.class);
		register(128216, ReqZoneCancelSignupToGameMessage.class, ReqZoneCancelSignupToGameHandler.class);
		register(129205, ReqStartShuffleRaffleMessage.class, ReqStartShuffleRaffleHandler.class);
		register(103215, ReqReportPlayerSpeedMessage.class, ReqReportPlayerSpeedHandler.class);
		register(100315, ReqJustCreateCharacterToGameMessage.class, ReqJustCreateCharacterToGameHandler.class);
		register(203303, ReqSyncPlayerInfoFromDataServerMessage.class, ReqSyncPlayerInfoFromDataServerHandler.class);
		register(203304, ResSyncPlayerInfoFromDataServerMessage.class, ResSyncPlayerInfoFromDataServerHandler.class);
		register(203306, ReqPlayerStateFromDataServerMessage.class, ReqPlayerStateFromDataServerHandler.class);
		register(203307, ResPlayerStateFromDataServerMessage.class, ResPlayerStateFromDataServerHandler.class);
		register(203308, ReqPlayerQuitToDataServerMessage.class, ReqPlayerQuitToDataServerHandler.class);
		register(203309, ResPlayerQuitToDataServerMessage.class, ResPlayerQuitToDataServerHandler.class);
		register(204301, ReqLoginCharacterToPublicGameMessage.class, ReqLoginCharacterToPublicGameHandler.class);
		register(204304, ReqQuitToPublicGameMessage.class, ReqQuitToPublicGameHandler.class);
		register(158201, ReqBreakthroughToGameMessage.class, ReqBreakthroughToGameHandler.class);
		register(158202, ReqIntensifyToGameMessage.class, ReqIntensifyToGameHandler.class);
		register(159201, ReqWineShowPanelMessage.class, ReqWineShowPanelHandler.class);
		register(159202, ReqWineRandomMessage.class, ReqWineRandomHandler.class);
		register(159203, ReqWineMoneyChangeMessage.class, ReqWineMoneyChangeHandler.class);
		register(159204, ReqWineGoldChangeMessage.class, ReqWineGoldChangeHandler.class);
		register(159205, ReqWineGetPrizeMessage.class, ReqWineGetPrizeHandler.class);
		register(146207, ReqCountryOpenTopToGameMessage.class, ReqCountryOpenTopToGameHandler.class);
		register(121325, ResFriendGuildListToGameMessage.class, ResFriendGuildListToGameHandler.class);
		register(121326, ResFriendGuildToGameMessage.class, ResFriendGuildToGameHandler.class);
		register(203310, ReqSyncPlayerCrossToDataServerMessage.class, ReqSyncPlayerCrossToDataServerHandler.class);
		register(203311, ResSyncPlayerCrossToDataServerMessage.class, ResSyncPlayerCrossToDataServerHandler.class);
		register(203312, ReqPlayerCrossFromDataServerMessage.class, ReqPlayerCrossFromDataServerHandler.class);
		register(203313, ResPlayerCrossFromDataServerMessage.class, ResPlayerCrossFromDataServerHandler.class);
		register(203314, ResPlayerCrossFromDataServerErrorMessage.class, ResPlayerCrossFromDataServerErrorHandler.class);
		register(203315, ReqKickPlayerToCrossServerMessage.class, ReqKickPlayerToCrossServerHandler.class);
		register(203305, ResSyncPlayerInfoFromDataServerErrorMessage.class, ResSyncPlayerInfoFromDataServerErrorHandler.class);
		register(160200, ReqBagSynMessage.class, ReqBagSynHandler.class);
		register(160201, ReqBagItemMoveMessage.class, ReqBagItemMoveHandler.class);
		register(160202, ReqBagItemMoveInMessage.class, ReqBagItemMoveInHandler.class);
		register(160203, ReqBagItemMoveOutMessage.class, ReqBagItemMoveOutHandler.class);
		register(161301, ResSystemgrantRefreshToGameMessage.class, ResSystemgrantRefreshToGameHandler.class);
		register(162201, ReqGetHiddenWeaponInfoMessage.class, ReqGetHiddenWeaponInfoHandler.class);
		register(162202, ReqWearHiddenWeaponStateMessage.class, ReqWearHiddenWeaponStateHandler.class);
		register(162203, ReqHiddenWeaponStageUpPanelMessage.class, ReqHiddenWeaponStageUpPanelHandler.class);
		register(162204, ReqHiddenWeaponStageUpStartMessage.class, ReqHiddenWeaponStageUpStartHandler.class);
		register(163201, ReqLaunchProposeToGameMessage.class, ReqLaunchProposeToGameHandler.class);
		register(163202, ReqLaunchProposeStartToGameMessage.class, ReqLaunchProposeStartToGameHandler.class);
		register(163203, ReqProposeSelectToGameMessage.class, ReqProposeSelectToGameHandler.class);
		register(163204, ReqReplaceRingToGameMessage.class, ReqReplaceRingToGameHandler.class);
		register(163205, ReqNewLeaveMsgToGameMessage.class, ReqNewLeaveMsgToGameHandler.class);
		register(163206, ReqDivorceToGameMessage.class, ReqDivorceToGameHandler.class);
		register(163207, ReqApplyWeddingToGameMessage.class, ReqApplyWeddingToGameHandler.class);
		register(163208, ReqDivorceSelectToGameMessage.class, ReqDivorceSelectToGameHandler.class);
		register(163209, ReqSpouseInfoToGameMessage.class, ReqSpouseInfoToGameHandler.class);
		register(163210, ReqRedEnvelopeToGameMessage.class, ReqRedEnvelopeToGameHandler.class);
		register(163211, ReqWeddingListToGameMessage.class, ReqWeddingListToGameHandler.class);
		register(163212, ReqWeddingParticipateToGameMessage.class, ReqWeddingParticipateToGameHandler.class);
		register(163213, ReqWeddingEatingToGameMessage.class, ReqWeddingEatingToGameHandler.class);
		register(163214, ReqReceiveredenvelopeToGameMessage.class, ReqReceiveredenvelopeToGameHandler.class);
		register(163215, ReqCockRedenvelopeToGameMessage.class, ReqCockRedenvelopeToGameHandler.class);
		register(163216, ReqTeaseSpouseToGameMessage.class, ReqTeaseSpouseToGameHandler.class);
		register(163217, ReqGetSpouseOtherToGameMessage.class, ReqGetSpouseOtherToGameHandler.class);
		register(163218, ReqSpouseMoveToGameMessage.class, ReqSpouseMoveToGameHandler.class);
		register(163219, ReqDeleteLeaveMsgToGameMessage.class, ReqDeleteLeaveMsgToGameHandler.class);
		register(163220, ReqChangeRingToGameMessage.class, ReqChangeRingToGameHandler.class);
		register(162205, ReqHiddenWeaponStudySkillMessage.class, ReqHiddenWeaponStudySkillHandler.class);
		register(136205, ReqCohesionZhenQiMessage.class, ReqCohesionZhenQiHandler.class);
		register(164201, ReqSelectIsSetToGameMessage.class, ReqSelectIsSetToGameHandler.class);
		register(164202, ReqPasswordSetToGameMessage.class, ReqPasswordSetToGameHandler.class);
		register(164203, ReqVerificationToGameMessage.class, ReqVerificationToGameHandler.class);
		register(164204, ReqPasswordUnlockToGameMessage.class, ReqPasswordUnlockToGameHandler.class);
		register(164205, ReqModifyPasswordToGameMessage.class, ReqModifyPasswordToGameHandler.class);
		register(164206, ReqForgetPasswordToGameMessage.class, ReqForgetPasswordToGameHandler.class);
		register(164301, ReqBackstageModifyToGameMessage.class, ReqBackstageModifyToGameHandler.class);
		register(138204, ReqReceiveMobileGiftMessage.class, ReqReceiveMobileGiftHandler.class);
		register(138205, ReqReceiveMobileGiftInfoMessage.class, ReqReceiveMobileGiftInfoHandler.class);
	}
	
	private void register(int id, Class<?> messageClass, Class<?> handlerClass){
		messages.put(id, messageClass);
		if(handlerClass!=null) handlers.put(id, handlerClass);
	}
	
	/**
	 * 获取消息体
	 * @param id
	 * @return
	 * @throws InstantiationException
	 * @throws IllegalAccessException
	 */
	public Message getMessage(int id) throws InstantiationException, IllegalAccessException{
		if(!messages.containsKey(id)){
			return null;
		}else{
			return (Message)messages.get(id).newInstance();
		}
	}
	
	/**
	 * 获取处理函数
	 * @param id
	 * @return
	 * @throws InstantiationException
	 * @throws IllegalAccessException
	 */
	public Handler getHandler(int id) throws InstantiationException, IllegalAccessException{
		if(!handlers.containsKey(id)){
			return null;
		}else{
			return (Handler)handlers.get(id).newInstance();
		}
	}
}